/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentmapDotjsonRouteImport } from './routes/agentmap[.]json'
import { Route as AiDottxtRouteImport } from './routes/ai[.]txt'
import { Route as DiscoveryDotjsonRouteImport } from './routes/discovery[.]json'
import { Route as GrowRouteImport } from './routes/grow'
import { Route as ListRouteImport } from './routes/list'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as RobotsAgentDottxtRouteImport } from './routes/robots-agent[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SkillDotjsonRouteImport } from './routes/skill[.]json'
import { Route as TalkRouteImport } from './routes/talk'
import { Route as DotwellKnownA2aCardDotjsonRouteImport } from './routes/[.]well-known/a2a-card[.]json'
import { Route as DotwellKnownAgentCardDotjsonRouteImport } from './routes/[.]well-known/agent-card[.]json'
import { Route as DotwellKnownAgentDescriptionsRouteImport } from './routes/[.]well-known/agent-descriptions'
import { Route as DotwellKnownAgentDotjsonRouteImport } from './routes/[.]well-known/agent[.]json'
import { Route as DotwellKnownAgentmapDotjsonRouteImport } from './routes/[.]well-known/agentmap[.]json'
import { Route as DotwellKnownAgentsRouteImport } from './routes/[.]well-known/agents'
import { Route as DotwellKnownAiCatalogDotjsonRouteImport } from './routes/[.]well-known/ai-catalog[.]json'
import { Route as DotwellKnownHttpMessageSignaturesDirectoryRouteImport } from './routes/[.]well-known/http-message-signatures-directory'
import { Route as DotwellKnownJwksDotjsonRouteImport } from './routes/[.]well-known/jwks[.]json'
import { Route as DotwellKnownMcpRegistryAuthRouteImport } from './routes/[.]well-known/mcp-registry-auth'
import { Route as DotwellKnownMcpDotjsonRouteImport } from './routes/[.]well-known/mcp[.]json'
import { Route as DotwellKnownSignatureAgentCardDotjsonRouteImport } from './routes/[.]well-known/signature-agent-card[.]json'
import { Route as AgentsPublicRouteImport } from './routes/agents/public'
import { Route as AgentsSearchRouteImport } from './routes/agents/search'
import { Route as ApiA2aRouteImport } from './routes/api/a2a'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiCountersRouteImport } from './routes/api/counters'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiGrowthRouteImport } from './routes/api/growth'
import { Route as ApiListingLanesRouteImport } from './routes/api/listing-lanes'
import { Route as ApiMatchRouteImport } from './routes/api/match'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiProtocolRouteImport } from './routes/api/protocol'
import { Route as ApiPublishRouteImport } from './routes/api/publish'
import { Route as ApiScoreRouteImport } from './routes/api/score'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiTalkRouteImport } from './routes/api/talk'
import { Route as BadgeKindRouteImport } from './routes/badge/$kind'
import { Route as ForAgentsIndexRouteImport } from './routes/for-agents/index'
import { Route as ListStatusRouteImport } from './routes/list/status'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsImprovementLogRouteImport } from './routes/products/improvement-log'
import { Route as ProductsRoadmapRouteImport } from './routes/products/roadmap'
import { Route as ProductsSuccessRouteImport } from './routes/products/success'
import { Route as SkillsDualregistryDotmdRouteImport } from './routes/skills/dualregistry[.]md'
import { Route as DotwellKnownMcpServerCardRouteImport } from './routes/[.]well-known/mcp/server-card'
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from './routes/[.]well-known/mcp/server-card[.]json'
import { Route as ApiArdSearchRouteImport } from './routes/api/ard/search'
import { Route as ApiCronPrefilterRouteImport } from './routes/api/cron/prefilter'
import { Route as ApiCronProbeRouteImport } from './routes/api/cron/probe'
import { Route as ApiDnsMcpStatusRouteImport } from './routes/api/dns/mcp-status'
import { Route as ApiFunnelIndexRouteImport } from './routes/api/funnel/index'
import { Route as ApiListingsActiveRouteImport } from './routes/api/listings/active'
import { Route as ApiListingsStatusRouteImport } from './routes/api/listings/status'
import { Route as ApiMcpRegistryPublishStatusRouteImport } from './routes/api/mcp-registry/publish-status'
import { Route as ApiMcpRegistryServerDotjsonRouteImport } from './routes/api/mcp-registry/server[.]json'
import { Route as ApiOpsAgentRunsRouteImport } from './routes/api/ops/agent-runs'
import { Route as ApiOpsCloudflareApplyRouteImport } from './routes/api/ops/cloudflare-apply'
import { Route as ApiOpsVercelCostRouteImport } from './routes/api/ops/vercel-cost'
import { Route as ApiProbesIndexRouteImport } from './routes/api/probes/index'
import { Route as ApiProductsAccessRouteImport } from './routes/api/products/access'
import { Route as ApiProductsAgentRouteImport } from './routes/api/products/agent'
import { Route as ApiProductsAgentfinderRouteImport } from './routes/api/products/agentfinder'
import { Route as ApiProductsAutocatalysisRouteImport } from './routes/api/products/autocatalysis'
import { Route as ApiProductsCheckoutRouteImport } from './routes/api/products/checkout'
import { Route as ApiProductsConfirmRouteImport } from './routes/api/products/confirm'
import { Route as ApiProductsConversionRouteImport } from './routes/api/products/conversion'
import { Route as ApiProductsConversionPressureRouteImport } from './routes/api/products/conversion-pressure'
import { Route as ApiProductsDemoRouteImport } from './routes/api/products/demo'
import { Route as ApiProductsDemoConfirmRouteImport } from './routes/api/products/demo-confirm'
import { Route as ApiProductsDemoNudgeRouteImport } from './routes/api/products/demo-nudge'
import { Route as ApiProductsDiscoveryPackRouteImport } from './routes/api/products/discovery-pack'
import { Route as ApiProductsDualStrategyRouteImport } from './routes/api/products/dual-strategy'
import { Route as ApiProductsExonomicsRouteImport } from './routes/api/products/exonomics'
import { Route as ApiProductsExportRouteImport } from './routes/api/products/export'
import { Route as ApiProductsFederationRouteImport } from './routes/api/products/federation'
import { Route as ApiProductsFeedbackRouteImport } from './routes/api/products/feedback'
import { Route as ApiProductsFeedbackDriveRouteImport } from './routes/api/products/feedback-drive'
import { Route as ApiProductsFirstPrinciplesRouteImport } from './routes/api/products/first-principles'
import { Route as ApiProductsFoundingDogfoodRouteImport } from './routes/api/products/founding-dogfood'
import { Route as ApiProductsGoHarderRouteImport } from './routes/api/products/go-harder'
import { Route as ApiProductsImprovementLogRouteImport } from './routes/api/products/improvement-log'
import { Route as ApiProductsInteropRouteImport } from './routes/api/products/interop'
import { Route as ApiProductsLearningRouteImport } from './routes/api/products/learning'
import { Route as ApiProductsLifecycleRouteImport } from './routes/api/products/lifecycle'
import { Route as ApiProductsMailRouteImport } from './routes/api/products/mail'
import { Route as ApiProductsPreferencesRouteImport } from './routes/api/products/preferences'
import { Route as ApiProductsPreviewRouteImport } from './routes/api/products/preview'
import { Route as ApiProductsReciprocityRouteImport } from './routes/api/products/reciprocity'
import { Route as ApiProductsReplyCaptureRouteImport } from './routes/api/products/reply-capture'
import { Route as ApiProductsReviewRouteImport } from './routes/api/products/review'
import { Route as ApiProductsRoadmapRouteImport } from './routes/api/products/roadmap'
import { Route as ApiProductsRunRouteImport } from './routes/api/products/run'
import { Route as ApiProductsSelfLoopRouteImport } from './routes/api/products/self-loop'
import { Route as ApiProductsShipCadenceRouteImport } from './routes/api/products/ship-cadence'
import { Route as ApiProductsStigmergyRouteImport } from './routes/api/products/stigmergy'
import { Route as ApiProductsVerifyRouteImport } from './routes/api/products/verify'
import { Route as ApiProductsWebhookRouteImport } from './routes/api/products/webhook'
import { Route as ApiProductsWtpRouteImport } from './routes/api/products/wtp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentmapDotjsonRoute = AgentmapDotjsonRouteImport.update({
  id: '/agentmap.json',
  path: '/agentmap.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDottxtRoute = AiDottxtRouteImport.update({
  id: '/ai.txt',
  path: '/ai.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryDotjsonRoute = DiscoveryDotjsonRouteImport.update({
  id: '/discovery.json',
  path: '/discovery.json',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowRoute = GrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsAgentDottxtRoute = RobotsAgentDottxtRouteImport.update({
  id: '/robots-agent.txt',
  path: '/robots-agent.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillDotjsonRoute = SkillDotjsonRouteImport.update({
  id: '/skill.json',
  path: '/skill.json',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkRoute = TalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownA2aCardDotjsonRoute =
  DotwellKnownA2aCardDotjsonRouteImport.update({
    id: '/.well-known/a2a-card.json',
    path: '/.well-known/a2a-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentCardDotjsonRoute =
  DotwellKnownAgentCardDotjsonRouteImport.update({
    id: '/.well-known/agent-card.json',
    path: '/.well-known/agent-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentDescriptionsRoute =
  DotwellKnownAgentDescriptionsRouteImport.update({
    id: '/.well-known/agent-descriptions',
    path: '/.well-known/agent-descriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentDotjsonRoute =
  DotwellKnownAgentDotjsonRouteImport.update({
    id: '/.well-known/agent.json',
    path: '/.well-known/agent.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentmapDotjsonRoute =
  DotwellKnownAgentmapDotjsonRouteImport.update({
    id: '/.well-known/agentmap.json',
    path: '/.well-known/agentmap.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentsRoute = DotwellKnownAgentsRouteImport.update({
  id: '/.well-known/agents',
  path: '/.well-known/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAiCatalogDotjsonRoute =
  DotwellKnownAiCatalogDotjsonRouteImport.update({
    id: '/.well-known/ai-catalog.json',
    path: '/.well-known/ai-catalog.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownHttpMessageSignaturesDirectoryRoute =
  DotwellKnownHttpMessageSignaturesDirectoryRouteImport.update({
    id: '/.well-known/http-message-signatures-directory',
    path: '/.well-known/http-message-signatures-directory',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownJwksDotjsonRoute = DotwellKnownJwksDotjsonRouteImport.update({
  id: '/.well-known/jwks.json',
  path: '/.well-known/jwks.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMcpRegistryAuthRoute =
  DotwellKnownMcpRegistryAuthRouteImport.update({
    id: '/.well-known/mcp-registry-auth',
    path: '/.well-known/mcp-registry-auth',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownMcpDotjsonRoute = DotwellKnownMcpDotjsonRouteImport.update({
  id: '/.well-known/mcp.json',
  path: '/.well-known/mcp.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownSignatureAgentCardDotjsonRoute =
  DotwellKnownSignatureAgentCardDotjsonRouteImport.update({
    id: '/.well-known/signature-agent-card.json',
    path: '/.well-known/signature-agent-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentsPublicRoute = AgentsPublicRouteImport.update({
  id: '/agents/public',
  path: '/agents/public',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSearchRoute = AgentsSearchRouteImport.update({
  id: '/agents/search',
  path: '/agents/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA2aRoute = ApiA2aRouteImport.update({
  id: '/api/a2a',
  path: '/api/a2a',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountersRoute = ApiCountersRouteImport.update({
  id: '/api/counters',
  path: '/api/counters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrowthRoute = ApiGrowthRouteImport.update({
  id: '/api/growth',
  path: '/api/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListingLanesRoute = ApiListingLanesRouteImport.update({
  id: '/api/listing-lanes',
  path: '/api/listing-lanes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchRoute = ApiMatchRouteImport.update({
  id: '/api/match',
  path: '/api/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtocolRoute = ApiProtocolRouteImport.update({
  id: '/api/protocol',
  path: '/api/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishRoute = ApiPublishRouteImport.update({
  id: '/api/publish',
  path: '/api/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoreRoute = ApiScoreRouteImport.update({
  id: '/api/score',
  path: '/api/score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTalkRoute = ApiTalkRouteImport.update({
  id: '/api/talk',
  path: '/api/talk',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgeKindRoute = BadgeKindRouteImport.update({
  id: '/badge/$kind',
  path: '/badge/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgentsIndexRoute = ForAgentsIndexRouteImport.update({
  id: '/for-agents/',
  path: '/for-agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListStatusRoute = ListStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ListRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsImprovementLogRoute = ProductsImprovementLogRouteImport.update({
  id: '/products/improvement-log',
  path: '/products/improvement-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoadmapRoute = ProductsRoadmapRouteImport.update({
  id: '/products/roadmap',
  path: '/products/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSuccessRoute = ProductsSuccessRouteImport.update({
  id: '/products/success',
  path: '/products/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsDualregistryDotmdRoute = SkillsDualregistryDotmdRouteImport.update({
  id: '/skills/dualregistry.md',
  path: '/skills/dualregistry.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMcpServerCardRoute =
  DotwellKnownMcpServerCardRouteImport.update({
    id: '/.well-known/mcp/server-card',
    path: '/.well-known/mcp/server-card',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/.well-known/mcp/server-card.json',
    path: '/.well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiArdSearchRoute = ApiArdSearchRouteImport.update({
  id: '/api/ard/search',
  path: '/api/ard/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPrefilterRoute = ApiCronPrefilterRouteImport.update({
  id: '/api/cron/prefilter',
  path: '/api/cron/prefilter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronProbeRoute = ApiCronProbeRouteImport.update({
  id: '/api/cron/probe',
  path: '/api/cron/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDnsMcpStatusRoute = ApiDnsMcpStatusRouteImport.update({
  id: '/api/dns/mcp-status',
  path: '/api/dns/mcp-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFunnelIndexRoute = ApiFunnelIndexRouteImport.update({
  id: '/api/funnel/',
  path: '/api/funnel/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListingsActiveRoute = ApiListingsActiveRouteImport.update({
  id: '/api/listings/active',
  path: '/api/listings/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListingsStatusRoute = ApiListingsStatusRouteImport.update({
  id: '/api/listings/status',
  path: '/api/listings/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRegistryPublishStatusRoute =
  ApiMcpRegistryPublishStatusRouteImport.update({
    id: '/api/mcp-registry/publish-status',
    path: '/api/mcp-registry/publish-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMcpRegistryServerDotjsonRoute =
  ApiMcpRegistryServerDotjsonRouteImport.update({
    id: '/api/mcp-registry/server.json',
    path: '/api/mcp-registry/server.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpsAgentRunsRoute = ApiOpsAgentRunsRouteImport.update({
  id: '/api/ops/agent-runs',
  path: '/api/ops/agent-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsCloudflareApplyRoute = ApiOpsCloudflareApplyRouteImport.update({
  id: '/api/ops/cloudflare-apply',
  path: '/api/ops/cloudflare-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsVercelCostRoute = ApiOpsVercelCostRouteImport.update({
  id: '/api/ops/vercel-cost',
  path: '/api/ops/vercel-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProbesIndexRoute = ApiProbesIndexRouteImport.update({
  id: '/api/probes/',
  path: '/api/probes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsAccessRoute = ApiProductsAccessRouteImport.update({
  id: '/api/products/access',
  path: '/api/products/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsAgentRoute = ApiProductsAgentRouteImport.update({
  id: '/api/products/agent',
  path: '/api/products/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsAgentfinderRoute = ApiProductsAgentfinderRouteImport.update({
  id: '/api/products/agentfinder',
  path: '/api/products/agentfinder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsAutocatalysisRoute =
  ApiProductsAutocatalysisRouteImport.update({
    id: '/api/products/autocatalysis',
    path: '/api/products/autocatalysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProductsCheckoutRoute = ApiProductsCheckoutRouteImport.update({
  id: '/api/products/checkout',
  path: '/api/products/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsConfirmRoute = ApiProductsConfirmRouteImport.update({
  id: '/api/products/confirm',
  path: '/api/products/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsConversionRoute = ApiProductsConversionRouteImport.update({
  id: '/api/products/conversion',
  path: '/api/products/conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsConversionPressureRoute =
  ApiProductsConversionPressureRouteImport.update({
    id: '/api/products/conversion-pressure',
    path: '/api/products/conversion-pressure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProductsDemoRoute = ApiProductsDemoRouteImport.update({
  id: '/api/products/demo',
  path: '/api/products/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsDemoConfirmRoute = ApiProductsDemoConfirmRouteImport.update({
  id: '/api/products/demo-confirm',
  path: '/api/products/demo-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsDemoNudgeRoute = ApiProductsDemoNudgeRouteImport.update({
  id: '/api/products/demo-nudge',
  path: '/api/products/demo-nudge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsDiscoveryPackRoute =
  ApiProductsDiscoveryPackRouteImport.update({
    id: '/api/products/discovery-pack',
    path: '/api/products/discovery-pack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProductsDualStrategyRoute = ApiProductsDualStrategyRouteImport.update({
  id: '/api/products/dual-strategy',
  path: '/api/products/dual-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsExonomicsRoute = ApiProductsExonomicsRouteImport.update({
  id: '/api/products/exonomics',
  path: '/api/products/exonomics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsExportRoute = ApiProductsExportRouteImport.update({
  id: '/api/products/export',
  path: '/api/products/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsFederationRoute = ApiProductsFederationRouteImport.update({
  id: '/api/products/federation',
  path: '/api/products/federation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsFeedbackRoute = ApiProductsFeedbackRouteImport.update({
  id: '/api/products/feedback',
  path: '/api/products/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsFeedbackDriveRoute =
  ApiProductsFeedbackDriveRouteImport.update({
    id: '/api/products/feedback-drive',
    path: '/api/products/feedback-drive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProductsFirstPrinciplesRoute =
  ApiProductsFirstPrinciplesRouteImport.update({
    id: '/api/products/first-principles',
    path: '/api/products/first-principles',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProductsFoundingDogfoodRoute =
  ApiProductsFoundingDogfoodRouteImport.update({
    id: '/api/products/founding-dogfood',
    path: '/api/products/founding-dogfood',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProductsGoHarderRoute = ApiProductsGoHarderRouteImport.update({
  id: '/api/products/go-harder',
  path: '/api/products/go-harder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsImprovementLogRoute =
  ApiProductsImprovementLogRouteImport.update({
    id: '/api/products/improvement-log',
    path: '/api/products/improvement-log',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProductsInteropRoute = ApiProductsInteropRouteImport.update({
  id: '/api/products/interop',
  path: '/api/products/interop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsLearningRoute = ApiProductsLearningRouteImport.update({
  id: '/api/products/learning',
  path: '/api/products/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsLifecycleRoute = ApiProductsLifecycleRouteImport.update({
  id: '/api/products/lifecycle',
  path: '/api/products/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsMailRoute = ApiProductsMailRouteImport.update({
  id: '/api/products/mail',
  path: '/api/products/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsPreferencesRoute = ApiProductsPreferencesRouteImport.update({
  id: '/api/products/preferences',
  path: '/api/products/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsPreviewRoute = ApiProductsPreviewRouteImport.update({
  id: '/api/products/preview',
  path: '/api/products/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsReciprocityRoute = ApiProductsReciprocityRouteImport.update({
  id: '/api/products/reciprocity',
  path: '/api/products/reciprocity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsReplyCaptureRoute = ApiProductsReplyCaptureRouteImport.update({
  id: '/api/products/reply-capture',
  path: '/api/products/reply-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsReviewRoute = ApiProductsReviewRouteImport.update({
  id: '/api/products/review',
  path: '/api/products/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoadmapRoute = ApiProductsRoadmapRouteImport.update({
  id: '/api/products/roadmap',
  path: '/api/products/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRunRoute = ApiProductsRunRouteImport.update({
  id: '/api/products/run',
  path: '/api/products/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsSelfLoopRoute = ApiProductsSelfLoopRouteImport.update({
  id: '/api/products/self-loop',
  path: '/api/products/self-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsShipCadenceRoute = ApiProductsShipCadenceRouteImport.update({
  id: '/api/products/ship-cadence',
  path: '/api/products/ship-cadence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsStigmergyRoute = ApiProductsStigmergyRouteImport.update({
  id: '/api/products/stigmergy',
  path: '/api/products/stigmergy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsVerifyRoute = ApiProductsVerifyRouteImport.update({
  id: '/api/products/verify',
  path: '/api/products/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsWebhookRoute = ApiProductsWebhookRouteImport.update({
  id: '/api/products/webhook',
  path: '/api/products/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsWtpRoute = ApiProductsWtpRouteImport.update({
  id: '/api/products/wtp',
  path: '/api/products/wtp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentmap.json': typeof AgentmapDotjsonRoute
  '/ai.txt': typeof AiDottxtRoute
  '/discovery.json': typeof DiscoveryDotjsonRoute
  '/grow': typeof GrowRoute
  '/list': typeof ListRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots-agent.txt': typeof RobotsAgentDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skill.json': typeof SkillDotjsonRoute
  '/talk': typeof TalkRoute
  '/.well-known/a2a-card.json': typeof DotwellKnownA2aCardDotjsonRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent-descriptions': typeof DotwellKnownAgentDescriptionsRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/agentmap.json': typeof DotwellKnownAgentmapDotjsonRoute
  '/.well-known/agents': typeof DotwellKnownAgentsRoute
  '/.well-known/ai-catalog.json': typeof DotwellKnownAiCatalogDotjsonRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/mcp-registry-auth': typeof DotwellKnownMcpRegistryAuthRoute
  '/.well-known/mcp.json': typeof DotwellKnownMcpDotjsonRoute
  '/.well-known/signature-agent-card.json': typeof DotwellKnownSignatureAgentCardDotjsonRoute
  '/agents/public': typeof AgentsPublicRoute
  '/agents/search': typeof AgentsSearchRoute
  '/api/a2a': typeof ApiA2aRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/counters': typeof ApiCountersRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/growth': typeof ApiGrowthRoute
  '/api/listing-lanes': typeof ApiListingLanesRoute
  '/api/match': typeof ApiMatchRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/protocol': typeof ApiProtocolRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/score': typeof ApiScoreRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/talk': typeof ApiTalkRoute
  '/badge/$kind': typeof BadgeKindRoute
  '/list/status': typeof ListStatusRoute
  '/products/improvement-log': typeof ProductsImprovementLogRoute
  '/products/roadmap': typeof ProductsRoadmapRoute
  '/products/success': typeof ProductsSuccessRoute
  '/skills/dualregistry.md': typeof SkillsDualregistryDotmdRoute
  '/for-agents/': typeof ForAgentsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/.well-known/mcp/server-card': typeof DotwellKnownMcpServerCardRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/ard/search': typeof ApiArdSearchRoute
  '/api/cron/prefilter': typeof ApiCronPrefilterRoute
  '/api/cron/probe': typeof ApiCronProbeRoute
  '/api/dns/mcp-status': typeof ApiDnsMcpStatusRoute
  '/api/listings/active': typeof ApiListingsActiveRoute
  '/api/listings/status': typeof ApiListingsStatusRoute
  '/api/mcp-registry/publish-status': typeof ApiMcpRegistryPublishStatusRoute
  '/api/mcp-registry/server.json': typeof ApiMcpRegistryServerDotjsonRoute
  '/api/ops/agent-runs': typeof ApiOpsAgentRunsRoute
  '/api/ops/cloudflare-apply': typeof ApiOpsCloudflareApplyRoute
  '/api/ops/vercel-cost': typeof ApiOpsVercelCostRoute
  '/api/products/access': typeof ApiProductsAccessRoute
  '/api/products/agent': typeof ApiProductsAgentRoute
  '/api/products/agentfinder': typeof ApiProductsAgentfinderRoute
  '/api/products/autocatalysis': typeof ApiProductsAutocatalysisRoute
  '/api/products/checkout': typeof ApiProductsCheckoutRoute
  '/api/products/confirm': typeof ApiProductsConfirmRoute
  '/api/products/conversion': typeof ApiProductsConversionRoute
  '/api/products/conversion-pressure': typeof ApiProductsConversionPressureRoute
  '/api/products/demo': typeof ApiProductsDemoRoute
  '/api/products/demo-confirm': typeof ApiProductsDemoConfirmRoute
  '/api/products/demo-nudge': typeof ApiProductsDemoNudgeRoute
  '/api/products/discovery-pack': typeof ApiProductsDiscoveryPackRoute
  '/api/products/dual-strategy': typeof ApiProductsDualStrategyRoute
  '/api/products/exonomics': typeof ApiProductsExonomicsRoute
  '/api/products/export': typeof ApiProductsExportRoute
  '/api/products/federation': typeof ApiProductsFederationRoute
  '/api/products/feedback': typeof ApiProductsFeedbackRoute
  '/api/products/feedback-drive': typeof ApiProductsFeedbackDriveRoute
  '/api/products/first-principles': typeof ApiProductsFirstPrinciplesRoute
  '/api/products/founding-dogfood': typeof ApiProductsFoundingDogfoodRoute
  '/api/products/go-harder': typeof ApiProductsGoHarderRoute
  '/api/products/improvement-log': typeof ApiProductsImprovementLogRoute
  '/api/products/interop': typeof ApiProductsInteropRoute
  '/api/products/learning': typeof ApiProductsLearningRoute
  '/api/products/lifecycle': typeof ApiProductsLifecycleRoute
  '/api/products/mail': typeof ApiProductsMailRoute
  '/api/products/preferences': typeof ApiProductsPreferencesRoute
  '/api/products/preview': typeof ApiProductsPreviewRoute
  '/api/products/reciprocity': typeof ApiProductsReciprocityRoute
  '/api/products/reply-capture': typeof ApiProductsReplyCaptureRoute
  '/api/products/review': typeof ApiProductsReviewRoute
  '/api/products/roadmap': typeof ApiProductsRoadmapRoute
  '/api/products/run': typeof ApiProductsRunRoute
  '/api/products/self-loop': typeof ApiProductsSelfLoopRoute
  '/api/products/ship-cadence': typeof ApiProductsShipCadenceRoute
  '/api/products/stigmergy': typeof ApiProductsStigmergyRoute
  '/api/products/verify': typeof ApiProductsVerifyRoute
  '/api/products/webhook': typeof ApiProductsWebhookRoute
  '/api/products/wtp': typeof ApiProductsWtpRoute
  '/api/funnel/': typeof ApiFunnelIndexRoute
  '/api/probes/': typeof ApiProbesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentmap.json': typeof AgentmapDotjsonRoute
  '/ai.txt': typeof AiDottxtRoute
  '/discovery.json': typeof DiscoveryDotjsonRoute
  '/grow': typeof GrowRoute
  '/list': typeof ListRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots-agent.txt': typeof RobotsAgentDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skill.json': typeof SkillDotjsonRoute
  '/talk': typeof TalkRoute
  '/.well-known/a2a-card.json': typeof DotwellKnownA2aCardDotjsonRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent-descriptions': typeof DotwellKnownAgentDescriptionsRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/agentmap.json': typeof DotwellKnownAgentmapDotjsonRoute
  '/.well-known/agents': typeof DotwellKnownAgentsRoute
  '/.well-known/ai-catalog.json': typeof DotwellKnownAiCatalogDotjsonRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/mcp-registry-auth': typeof DotwellKnownMcpRegistryAuthRoute
  '/.well-known/mcp.json': typeof DotwellKnownMcpDotjsonRoute
  '/.well-known/signature-agent-card.json': typeof DotwellKnownSignatureAgentCardDotjsonRoute
  '/agents/public': typeof AgentsPublicRoute
  '/agents/search': typeof AgentsSearchRoute
  '/api/a2a': typeof ApiA2aRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/counters': typeof ApiCountersRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/growth': typeof ApiGrowthRoute
  '/api/listing-lanes': typeof ApiListingLanesRoute
  '/api/match': typeof ApiMatchRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/protocol': typeof ApiProtocolRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/score': typeof ApiScoreRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/talk': typeof ApiTalkRoute
  '/badge/$kind': typeof BadgeKindRoute
  '/list/status': typeof ListStatusRoute
  '/products/improvement-log': typeof ProductsImprovementLogRoute
  '/products/roadmap': typeof ProductsRoadmapRoute
  '/products/success': typeof ProductsSuccessRoute
  '/skills/dualregistry.md': typeof SkillsDualregistryDotmdRoute
  '/for-agents': typeof ForAgentsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/.well-known/mcp/server-card': typeof DotwellKnownMcpServerCardRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/ard/search': typeof ApiArdSearchRoute
  '/api/cron/prefilter': typeof ApiCronPrefilterRoute
  '/api/cron/probe': typeof ApiCronProbeRoute
  '/api/dns/mcp-status': typeof ApiDnsMcpStatusRoute
  '/api/listings/active': typeof ApiListingsActiveRoute
  '/api/listings/status': typeof ApiListingsStatusRoute
  '/api/mcp-registry/publish-status': typeof ApiMcpRegistryPublishStatusRoute
  '/api/mcp-registry/server.json': typeof ApiMcpRegistryServerDotjsonRoute
  '/api/ops/agent-runs': typeof ApiOpsAgentRunsRoute
  '/api/ops/cloudflare-apply': typeof ApiOpsCloudflareApplyRoute
  '/api/ops/vercel-cost': typeof ApiOpsVercelCostRoute
  '/api/products/access': typeof ApiProductsAccessRoute
  '/api/products/agent': typeof ApiProductsAgentRoute
  '/api/products/agentfinder': typeof ApiProductsAgentfinderRoute
  '/api/products/autocatalysis': typeof ApiProductsAutocatalysisRoute
  '/api/products/checkout': typeof ApiProductsCheckoutRoute
  '/api/products/confirm': typeof ApiProductsConfirmRoute
  '/api/products/conversion': typeof ApiProductsConversionRoute
  '/api/products/conversion-pressure': typeof ApiProductsConversionPressureRoute
  '/api/products/demo': typeof ApiProductsDemoRoute
  '/api/products/demo-confirm': typeof ApiProductsDemoConfirmRoute
  '/api/products/demo-nudge': typeof ApiProductsDemoNudgeRoute
  '/api/products/discovery-pack': typeof ApiProductsDiscoveryPackRoute
  '/api/products/dual-strategy': typeof ApiProductsDualStrategyRoute
  '/api/products/exonomics': typeof ApiProductsExonomicsRoute
  '/api/products/export': typeof ApiProductsExportRoute
  '/api/products/federation': typeof ApiProductsFederationRoute
  '/api/products/feedback': typeof ApiProductsFeedbackRoute
  '/api/products/feedback-drive': typeof ApiProductsFeedbackDriveRoute
  '/api/products/first-principles': typeof ApiProductsFirstPrinciplesRoute
  '/api/products/founding-dogfood': typeof ApiProductsFoundingDogfoodRoute
  '/api/products/go-harder': typeof ApiProductsGoHarderRoute
  '/api/products/improvement-log': typeof ApiProductsImprovementLogRoute
  '/api/products/interop': typeof ApiProductsInteropRoute
  '/api/products/learning': typeof ApiProductsLearningRoute
  '/api/products/lifecycle': typeof ApiProductsLifecycleRoute
  '/api/products/mail': typeof ApiProductsMailRoute
  '/api/products/preferences': typeof ApiProductsPreferencesRoute
  '/api/products/preview': typeof ApiProductsPreviewRoute
  '/api/products/reciprocity': typeof ApiProductsReciprocityRoute
  '/api/products/reply-capture': typeof ApiProductsReplyCaptureRoute
  '/api/products/review': typeof ApiProductsReviewRoute
  '/api/products/roadmap': typeof ApiProductsRoadmapRoute
  '/api/products/run': typeof ApiProductsRunRoute
  '/api/products/self-loop': typeof ApiProductsSelfLoopRoute
  '/api/products/ship-cadence': typeof ApiProductsShipCadenceRoute
  '/api/products/stigmergy': typeof ApiProductsStigmergyRoute
  '/api/products/verify': typeof ApiProductsVerifyRoute
  '/api/products/webhook': typeof ApiProductsWebhookRoute
  '/api/products/wtp': typeof ApiProductsWtpRoute
  '/api/funnel': typeof ApiFunnelIndexRoute
  '/api/probes': typeof ApiProbesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentmap.json': typeof AgentmapDotjsonRoute
  '/ai.txt': typeof AiDottxtRoute
  '/discovery.json': typeof DiscoveryDotjsonRoute
  '/grow': typeof GrowRoute
  '/list': typeof ListRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/robots-agent.txt': typeof RobotsAgentDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skill.json': typeof SkillDotjsonRoute
  '/talk': typeof TalkRoute
  '/.well-known/a2a-card.json': typeof DotwellKnownA2aCardDotjsonRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent-descriptions': typeof DotwellKnownAgentDescriptionsRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/agentmap.json': typeof DotwellKnownAgentmapDotjsonRoute
  '/.well-known/agents': typeof DotwellKnownAgentsRoute
  '/.well-known/ai-catalog.json': typeof DotwellKnownAiCatalogDotjsonRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/mcp-registry-auth': typeof DotwellKnownMcpRegistryAuthRoute
  '/.well-known/mcp.json': typeof DotwellKnownMcpDotjsonRoute
  '/.well-known/signature-agent-card.json': typeof DotwellKnownSignatureAgentCardDotjsonRoute
  '/agents/public': typeof AgentsPublicRoute
  '/agents/search': typeof AgentsSearchRoute
  '/api/a2a': typeof ApiA2aRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/counters': typeof ApiCountersRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/growth': typeof ApiGrowthRoute
  '/api/listing-lanes': typeof ApiListingLanesRoute
  '/api/match': typeof ApiMatchRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/protocol': typeof ApiProtocolRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/score': typeof ApiScoreRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/talk': typeof ApiTalkRoute
  '/badge/$kind': typeof BadgeKindRoute
  '/list/status': typeof ListStatusRoute
  '/products/improvement-log': typeof ProductsImprovementLogRoute
  '/products/roadmap': typeof ProductsRoadmapRoute
  '/products/success': typeof ProductsSuccessRoute
  '/skills/dualregistry.md': typeof SkillsDualregistryDotmdRoute
  '/for-agents/': typeof ForAgentsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/.well-known/mcp/server-card': typeof DotwellKnownMcpServerCardRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/ard/search': typeof ApiArdSearchRoute
  '/api/cron/prefilter': typeof ApiCronPrefilterRoute
  '/api/cron/probe': typeof ApiCronProbeRoute
  '/api/dns/mcp-status': typeof ApiDnsMcpStatusRoute
  '/api/listings/active': typeof ApiListingsActiveRoute
  '/api/listings/status': typeof ApiListingsStatusRoute
  '/api/mcp-registry/publish-status': typeof ApiMcpRegistryPublishStatusRoute
  '/api/mcp-registry/server.json': typeof ApiMcpRegistryServerDotjsonRoute
  '/api/ops/agent-runs': typeof ApiOpsAgentRunsRoute
  '/api/ops/cloudflare-apply': typeof ApiOpsCloudflareApplyRoute
  '/api/ops/vercel-cost': typeof ApiOpsVercelCostRoute
  '/api/products/access': typeof ApiProductsAccessRoute
  '/api/products/agent': typeof ApiProductsAgentRoute
  '/api/products/agentfinder': typeof ApiProductsAgentfinderRoute
  '/api/products/autocatalysis': typeof ApiProductsAutocatalysisRoute
  '/api/products/checkout': typeof ApiProductsCheckoutRoute
  '/api/products/confirm': typeof ApiProductsConfirmRoute
  '/api/products/conversion': typeof ApiProductsConversionRoute
  '/api/products/conversion-pressure': typeof ApiProductsConversionPressureRoute
  '/api/products/demo': typeof ApiProductsDemoRoute
  '/api/products/demo-confirm': typeof ApiProductsDemoConfirmRoute
  '/api/products/demo-nudge': typeof ApiProductsDemoNudgeRoute
  '/api/products/discovery-pack': typeof ApiProductsDiscoveryPackRoute
  '/api/products/dual-strategy': typeof ApiProductsDualStrategyRoute
  '/api/products/exonomics': typeof ApiProductsExonomicsRoute
  '/api/products/export': typeof ApiProductsExportRoute
  '/api/products/federation': typeof ApiProductsFederationRoute
  '/api/products/feedback': typeof ApiProductsFeedbackRoute
  '/api/products/feedback-drive': typeof ApiProductsFeedbackDriveRoute
  '/api/products/first-principles': typeof ApiProductsFirstPrinciplesRoute
  '/api/products/founding-dogfood': typeof ApiProductsFoundingDogfoodRoute
  '/api/products/go-harder': typeof ApiProductsGoHarderRoute
  '/api/products/improvement-log': typeof ApiProductsImprovementLogRoute
  '/api/products/interop': typeof ApiProductsInteropRoute
  '/api/products/learning': typeof ApiProductsLearningRoute
  '/api/products/lifecycle': typeof ApiProductsLifecycleRoute
  '/api/products/mail': typeof ApiProductsMailRoute
  '/api/products/preferences': typeof ApiProductsPreferencesRoute
  '/api/products/preview': typeof ApiProductsPreviewRoute
  '/api/products/reciprocity': typeof ApiProductsReciprocityRoute
  '/api/products/reply-capture': typeof ApiProductsReplyCaptureRoute
  '/api/products/review': typeof ApiProductsReviewRoute
  '/api/products/roadmap': typeof ApiProductsRoadmapRoute
  '/api/products/run': typeof ApiProductsRunRoute
  '/api/products/self-loop': typeof ApiProductsSelfLoopRoute
  '/api/products/ship-cadence': typeof ApiProductsShipCadenceRoute
  '/api/products/stigmergy': typeof ApiProductsStigmergyRoute
  '/api/products/verify': typeof ApiProductsVerifyRoute
  '/api/products/webhook': typeof ApiProductsWebhookRoute
  '/api/products/wtp': typeof ApiProductsWtpRoute
  '/api/funnel/': typeof ApiFunnelIndexRoute
  '/api/probes/': typeof ApiProbesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentmap.json'
    | '/ai.txt'
    | '/discovery.json'
    | '/grow'
    | '/list'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/mcp'
    | '/openapi.json'
    | '/robots-agent.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/skill.json'
    | '/talk'
    | '/.well-known/a2a-card.json'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent-descriptions'
    | '/.well-known/agent.json'
    | '/.well-known/agentmap.json'
    | '/.well-known/agents'
    | '/.well-known/ai-catalog.json'
    | '/.well-known/http-message-signatures-directory'
    | '/.well-known/jwks.json'
    | '/.well-known/mcp-registry-auth'
    | '/.well-known/mcp.json'
    | '/.well-known/signature-agent-card.json'
    | '/agents/public'
    | '/agents/search'
    | '/api/a2a'
    | '/api/catalog'
    | '/api/categories'
    | '/api/counters'
    | '/api/dashboard'
    | '/api/feed'
    | '/api/growth'
    | '/api/listing-lanes'
    | '/api/match'
    | '/api/mcp'
    | '/api/protocol'
    | '/api/publish'
    | '/api/score'
    | '/api/stats'
    | '/api/talk'
    | '/badge/$kind'
    | '/list/status'
    | '/products/improvement-log'
    | '/products/roadmap'
    | '/products/success'
    | '/skills/dualregistry.md'
    | '/for-agents/'
    | '/products/'
    | '/.well-known/mcp/server-card'
    | '/.well-known/mcp/server-card.json'
    | '/api/ard/search'
    | '/api/cron/prefilter'
    | '/api/cron/probe'
    | '/api/dns/mcp-status'
    | '/api/listings/active'
    | '/api/listings/status'
    | '/api/mcp-registry/publish-status'
    | '/api/mcp-registry/server.json'
    | '/api/ops/agent-runs'
    | '/api/ops/cloudflare-apply'
    | '/api/ops/vercel-cost'
    | '/api/products/access'
    | '/api/products/agent'
    | '/api/products/agentfinder'
    | '/api/products/autocatalysis'
    | '/api/products/checkout'
    | '/api/products/confirm'
    | '/api/products/conversion'
    | '/api/products/conversion-pressure'
    | '/api/products/demo'
    | '/api/products/demo-confirm'
    | '/api/products/demo-nudge'
    | '/api/products/discovery-pack'
    | '/api/products/dual-strategy'
    | '/api/products/exonomics'
    | '/api/products/export'
    | '/api/products/federation'
    | '/api/products/feedback'
    | '/api/products/feedback-drive'
    | '/api/products/first-principles'
    | '/api/products/founding-dogfood'
    | '/api/products/go-harder'
    | '/api/products/improvement-log'
    | '/api/products/interop'
    | '/api/products/learning'
    | '/api/products/lifecycle'
    | '/api/products/mail'
    | '/api/products/preferences'
    | '/api/products/preview'
    | '/api/products/reciprocity'
    | '/api/products/reply-capture'
    | '/api/products/review'
    | '/api/products/roadmap'
    | '/api/products/run'
    | '/api/products/self-loop'
    | '/api/products/ship-cadence'
    | '/api/products/stigmergy'
    | '/api/products/verify'
    | '/api/products/webhook'
    | '/api/products/wtp'
    | '/api/funnel/'
    | '/api/probes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentmap.json'
    | '/ai.txt'
    | '/discovery.json'
    | '/grow'
    | '/list'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/mcp'
    | '/openapi.json'
    | '/robots-agent.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/skill.json'
    | '/talk'
    | '/.well-known/a2a-card.json'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent-descriptions'
    | '/.well-known/agent.json'
    | '/.well-known/agentmap.json'
    | '/.well-known/agents'
    | '/.well-known/ai-catalog.json'
    | '/.well-known/http-message-signatures-directory'
    | '/.well-known/jwks.json'
    | '/.well-known/mcp-registry-auth'
    | '/.well-known/mcp.json'
    | '/.well-known/signature-agent-card.json'
    | '/agents/public'
    | '/agents/search'
    | '/api/a2a'
    | '/api/catalog'
    | '/api/categories'
    | '/api/counters'
    | '/api/dashboard'
    | '/api/feed'
    | '/api/growth'
    | '/api/listing-lanes'
    | '/api/match'
    | '/api/mcp'
    | '/api/protocol'
    | '/api/publish'
    | '/api/score'
    | '/api/stats'
    | '/api/talk'
    | '/badge/$kind'
    | '/list/status'
    | '/products/improvement-log'
    | '/products/roadmap'
    | '/products/success'
    | '/skills/dualregistry.md'
    | '/for-agents'
    | '/products'
    | '/.well-known/mcp/server-card'
    | '/.well-known/mcp/server-card.json'
    | '/api/ard/search'
    | '/api/cron/prefilter'
    | '/api/cron/probe'
    | '/api/dns/mcp-status'
    | '/api/listings/active'
    | '/api/listings/status'
    | '/api/mcp-registry/publish-status'
    | '/api/mcp-registry/server.json'
    | '/api/ops/agent-runs'
    | '/api/ops/cloudflare-apply'
    | '/api/ops/vercel-cost'
    | '/api/products/access'
    | '/api/products/agent'
    | '/api/products/agentfinder'
    | '/api/products/autocatalysis'
    | '/api/products/checkout'
    | '/api/products/confirm'
    | '/api/products/conversion'
    | '/api/products/conversion-pressure'
    | '/api/products/demo'
    | '/api/products/demo-confirm'
    | '/api/products/demo-nudge'
    | '/api/products/discovery-pack'
    | '/api/products/dual-strategy'
    | '/api/products/exonomics'
    | '/api/products/export'
    | '/api/products/federation'
    | '/api/products/feedback'
    | '/api/products/feedback-drive'
    | '/api/products/first-principles'
    | '/api/products/founding-dogfood'
    | '/api/products/go-harder'
    | '/api/products/improvement-log'
    | '/api/products/interop'
    | '/api/products/learning'
    | '/api/products/lifecycle'
    | '/api/products/mail'
    | '/api/products/preferences'
    | '/api/products/preview'
    | '/api/products/reciprocity'
    | '/api/products/reply-capture'
    | '/api/products/review'
    | '/api/products/roadmap'
    | '/api/products/run'
    | '/api/products/self-loop'
    | '/api/products/ship-cadence'
    | '/api/products/stigmergy'
    | '/api/products/verify'
    | '/api/products/webhook'
    | '/api/products/wtp'
    | '/api/funnel'
    | '/api/probes'
  id:
    | '__root__'
    | '/'
    | '/agentmap.json'
    | '/ai.txt'
    | '/discovery.json'
    | '/grow'
    | '/list'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/mcp'
    | '/openapi.json'
    | '/robots-agent.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/skill.json'
    | '/talk'
    | '/.well-known/a2a-card.json'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent-descriptions'
    | '/.well-known/agent.json'
    | '/.well-known/agentmap.json'
    | '/.well-known/agents'
    | '/.well-known/ai-catalog.json'
    | '/.well-known/http-message-signatures-directory'
    | '/.well-known/jwks.json'
    | '/.well-known/mcp-registry-auth'
    | '/.well-known/mcp.json'
    | '/.well-known/signature-agent-card.json'
    | '/agents/public'
    | '/agents/search'
    | '/api/a2a'
    | '/api/catalog'
    | '/api/categories'
    | '/api/counters'
    | '/api/dashboard'
    | '/api/feed'
    | '/api/growth'
    | '/api/listing-lanes'
    | '/api/match'
    | '/api/mcp'
    | '/api/protocol'
    | '/api/publish'
    | '/api/score'
    | '/api/stats'
    | '/api/talk'
    | '/badge/$kind'
    | '/list/status'
    | '/products/improvement-log'
    | '/products/roadmap'
    | '/products/success'
    | '/skills/dualregistry.md'
    | '/for-agents/'
    | '/products/'
    | '/.well-known/mcp/server-card'
    | '/.well-known/mcp/server-card.json'
    | '/api/ard/search'
    | '/api/cron/prefilter'
    | '/api/cron/probe'
    | '/api/dns/mcp-status'
    | '/api/listings/active'
    | '/api/listings/status'
    | '/api/mcp-registry/publish-status'
    | '/api/mcp-registry/server.json'
    | '/api/ops/agent-runs'
    | '/api/ops/cloudflare-apply'
    | '/api/ops/vercel-cost'
    | '/api/products/access'
    | '/api/products/agent'
    | '/api/products/agentfinder'
    | '/api/products/autocatalysis'
    | '/api/products/checkout'
    | '/api/products/confirm'
    | '/api/products/conversion'
    | '/api/products/conversion-pressure'
    | '/api/products/demo'
    | '/api/products/demo-confirm'
    | '/api/products/demo-nudge'
    | '/api/products/discovery-pack'
    | '/api/products/dual-strategy'
    | '/api/products/exonomics'
    | '/api/products/export'
    | '/api/products/federation'
    | '/api/products/feedback'
    | '/api/products/feedback-drive'
    | '/api/products/first-principles'
    | '/api/products/founding-dogfood'
    | '/api/products/go-harder'
    | '/api/products/improvement-log'
    | '/api/products/interop'
    | '/api/products/learning'
    | '/api/products/lifecycle'
    | '/api/products/mail'
    | '/api/products/preferences'
    | '/api/products/preview'
    | '/api/products/reciprocity'
    | '/api/products/reply-capture'
    | '/api/products/review'
    | '/api/products/roadmap'
    | '/api/products/run'
    | '/api/products/self-loop'
    | '/api/products/ship-cadence'
    | '/api/products/stigmergy'
    | '/api/products/verify'
    | '/api/products/webhook'
    | '/api/products/wtp'
    | '/api/funnel/'
    | '/api/probes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentmapDotjsonRoute: typeof AgentmapDotjsonRoute
  AiDottxtRoute: typeof AiDottxtRoute
  DiscoveryDotjsonRoute: typeof DiscoveryDotjsonRoute
  GrowRoute: typeof GrowRoute
  ListRoute: typeof ListRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  RobotsAgentDottxtRoute: typeof RobotsAgentDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillDotjsonRoute: typeof SkillDotjsonRoute
  TalkRoute: typeof TalkRoute
  DotwellKnownA2aCardDotjsonRoute: typeof DotwellKnownA2aCardDotjsonRoute
  DotwellKnownAgentCardDotjsonRoute: typeof DotwellKnownAgentCardDotjsonRoute
  DotwellKnownAgentDescriptionsRoute: typeof DotwellKnownAgentDescriptionsRoute
  DotwellKnownAgentDotjsonRoute: typeof DotwellKnownAgentDotjsonRoute
  DotwellKnownAgentmapDotjsonRoute: typeof DotwellKnownAgentmapDotjsonRoute
  DotwellKnownAgentsRoute: typeof DotwellKnownAgentsRoute
  DotwellKnownAiCatalogDotjsonRoute: typeof DotwellKnownAiCatalogDotjsonRoute
  DotwellKnownHttpMessageSignaturesDirectoryRoute: typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  DotwellKnownJwksDotjsonRoute: typeof DotwellKnownJwksDotjsonRoute
  DotwellKnownMcpRegistryAuthRoute: typeof DotwellKnownMcpRegistryAuthRoute
  DotwellKnownMcpDotjsonRoute: typeof DotwellKnownMcpDotjsonRoute
  DotwellKnownSignatureAgentCardDotjsonRoute: typeof DotwellKnownSignatureAgentCardDotjsonRoute
  AgentsPublicRoute: typeof AgentsPublicRoute
  AgentsSearchRoute: typeof AgentsSearchRoute
  ApiA2aRoute: typeof ApiA2aRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiCountersRoute: typeof ApiCountersRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiGrowthRoute: typeof ApiGrowthRoute
  ApiListingLanesRoute: typeof ApiListingLanesRoute
  ApiMatchRoute: typeof ApiMatchRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiProtocolRoute: typeof ApiProtocolRoute
  ApiPublishRoute: typeof ApiPublishRoute
  ApiScoreRoute: typeof ApiScoreRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiTalkRoute: typeof ApiTalkRoute
  BadgeKindRoute: typeof BadgeKindRoute
  ProductsImprovementLogRoute: typeof ProductsImprovementLogRoute
  ProductsRoadmapRoute: typeof ProductsRoadmapRoute
  ProductsSuccessRoute: typeof ProductsSuccessRoute
  SkillsDualregistryDotmdRoute: typeof SkillsDualregistryDotmdRoute
  ForAgentsIndexRoute: typeof ForAgentsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  DotwellKnownMcpServerCardRoute: typeof DotwellKnownMcpServerCardRoute
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute
  ApiArdSearchRoute: typeof ApiArdSearchRoute
  ApiCronPrefilterRoute: typeof ApiCronPrefilterRoute
  ApiCronProbeRoute: typeof ApiCronProbeRoute
  ApiDnsMcpStatusRoute: typeof ApiDnsMcpStatusRoute
  ApiListingsActiveRoute: typeof ApiListingsActiveRoute
  ApiListingsStatusRoute: typeof ApiListingsStatusRoute
  ApiMcpRegistryPublishStatusRoute: typeof ApiMcpRegistryPublishStatusRoute
  ApiMcpRegistryServerDotjsonRoute: typeof ApiMcpRegistryServerDotjsonRoute
  ApiOpsAgentRunsRoute: typeof ApiOpsAgentRunsRoute
  ApiOpsCloudflareApplyRoute: typeof ApiOpsCloudflareApplyRoute
  ApiOpsVercelCostRoute: typeof ApiOpsVercelCostRoute
  ApiProductsAccessRoute: typeof ApiProductsAccessRoute
  ApiProductsAgentRoute: typeof ApiProductsAgentRoute
  ApiProductsAgentfinderRoute: typeof ApiProductsAgentfinderRoute
  ApiProductsAutocatalysisRoute: typeof ApiProductsAutocatalysisRoute
  ApiProductsCheckoutRoute: typeof ApiProductsCheckoutRoute
  ApiProductsConfirmRoute: typeof ApiProductsConfirmRoute
  ApiProductsConversionRoute: typeof ApiProductsConversionRoute
  ApiProductsConversionPressureRoute: typeof ApiProductsConversionPressureRoute
  ApiProductsDemoRoute: typeof ApiProductsDemoRoute
  ApiProductsDemoConfirmRoute: typeof ApiProductsDemoConfirmRoute
  ApiProductsDemoNudgeRoute: typeof ApiProductsDemoNudgeRoute
  ApiProductsDiscoveryPackRoute: typeof ApiProductsDiscoveryPackRoute
  ApiProductsDualStrategyRoute: typeof ApiProductsDualStrategyRoute
  ApiProductsExonomicsRoute: typeof ApiProductsExonomicsRoute
  ApiProductsExportRoute: typeof ApiProductsExportRoute
  ApiProductsFederationRoute: typeof ApiProductsFederationRoute
  ApiProductsFeedbackRoute: typeof ApiProductsFeedbackRoute
  ApiProductsFeedbackDriveRoute: typeof ApiProductsFeedbackDriveRoute
  ApiProductsFirstPrinciplesRoute: typeof ApiProductsFirstPrinciplesRoute
  ApiProductsFoundingDogfoodRoute: typeof ApiProductsFoundingDogfoodRoute
  ApiProductsGoHarderRoute: typeof ApiProductsGoHarderRoute
  ApiProductsImprovementLogRoute: typeof ApiProductsImprovementLogRoute
  ApiProductsInteropRoute: typeof ApiProductsInteropRoute
  ApiProductsLearningRoute: typeof ApiProductsLearningRoute
  ApiProductsLifecycleRoute: typeof ApiProductsLifecycleRoute
  ApiProductsMailRoute: typeof ApiProductsMailRoute
  ApiProductsPreferencesRoute: typeof ApiProductsPreferencesRoute
  ApiProductsPreviewRoute: typeof ApiProductsPreviewRoute
  ApiProductsReciprocityRoute: typeof ApiProductsReciprocityRoute
  ApiProductsReplyCaptureRoute: typeof ApiProductsReplyCaptureRoute
  ApiProductsReviewRoute: typeof ApiProductsReviewRoute
  ApiProductsRoadmapRoute: typeof ApiProductsRoadmapRoute
  ApiProductsRunRoute: typeof ApiProductsRunRoute
  ApiProductsSelfLoopRoute: typeof ApiProductsSelfLoopRoute
  ApiProductsShipCadenceRoute: typeof ApiProductsShipCadenceRoute
  ApiProductsStigmergyRoute: typeof ApiProductsStigmergyRoute
  ApiProductsVerifyRoute: typeof ApiProductsVerifyRoute
  ApiProductsWebhookRoute: typeof ApiProductsWebhookRoute
  ApiProductsWtpRoute: typeof ApiProductsWtpRoute
  ApiFunnelIndexRoute: typeof ApiFunnelIndexRoute
  ApiProbesIndexRoute: typeof ApiProbesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentmap.json': {
      id: '/agentmap.json'
      path: '/agentmap.json'
      fullPath: '/agentmap.json'
      preLoaderRoute: typeof AgentmapDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai.txt': {
      id: '/ai.txt'
      path: '/ai.txt'
      fullPath: '/ai.txt'
      preLoaderRoute: typeof AiDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery.json': {
      id: '/discovery.json'
      path: '/discovery.json'
      fullPath: '/discovery.json'
      preLoaderRoute: typeof DiscoveryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow': {
      id: '/grow'
      path: '/grow'
      fullPath: '/grow'
      preLoaderRoute: typeof GrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots-agent.txt': {
      id: '/robots-agent.txt'
      path: '/robots-agent.txt'
      fullPath: '/robots-agent.txt'
      preLoaderRoute: typeof RobotsAgentDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill.json': {
      id: '/skill.json'
      path: '/skill.json'
      fullPath: '/skill.json'
      preLoaderRoute: typeof SkillDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk': {
      id: '/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof TalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/a2a-card.json': {
      id: '/.well-known/a2a-card.json'
      path: '/.well-known/a2a-card.json'
      fullPath: '/.well-known/a2a-card.json'
      preLoaderRoute: typeof DotwellKnownA2aCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-card.json': {
      id: '/.well-known/agent-card.json'
      path: '/.well-known/agent-card.json'
      fullPath: '/.well-known/agent-card.json'
      preLoaderRoute: typeof DotwellKnownAgentCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-descriptions': {
      id: '/.well-known/agent-descriptions'
      path: '/.well-known/agent-descriptions'
      fullPath: '/.well-known/agent-descriptions'
      preLoaderRoute: typeof DotwellKnownAgentDescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent.json': {
      id: '/.well-known/agent.json'
      path: '/.well-known/agent.json'
      fullPath: '/.well-known/agent.json'
      preLoaderRoute: typeof DotwellKnownAgentDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agentmap.json': {
      id: '/.well-known/agentmap.json'
      path: '/.well-known/agentmap.json'
      fullPath: '/.well-known/agentmap.json'
      preLoaderRoute: typeof DotwellKnownAgentmapDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agents': {
      id: '/.well-known/agents'
      path: '/.well-known/agents'
      fullPath: '/.well-known/agents'
      preLoaderRoute: typeof DotwellKnownAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/ai-catalog.json': {
      id: '/.well-known/ai-catalog.json'
      path: '/.well-known/ai-catalog.json'
      fullPath: '/.well-known/ai-catalog.json'
      preLoaderRoute: typeof DotwellKnownAiCatalogDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/http-message-signatures-directory': {
      id: '/.well-known/http-message-signatures-directory'
      path: '/.well-known/http-message-signatures-directory'
      fullPath: '/.well-known/http-message-signatures-directory'
      preLoaderRoute: typeof DotwellKnownHttpMessageSignaturesDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/jwks.json': {
      id: '/.well-known/jwks.json'
      path: '/.well-known/jwks.json'
      fullPath: '/.well-known/jwks.json'
      preLoaderRoute: typeof DotwellKnownJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp-registry-auth': {
      id: '/.well-known/mcp-registry-auth'
      path: '/.well-known/mcp-registry-auth'
      fullPath: '/.well-known/mcp-registry-auth'
      preLoaderRoute: typeof DotwellKnownMcpRegistryAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp.json': {
      id: '/.well-known/mcp.json'
      path: '/.well-known/mcp.json'
      fullPath: '/.well-known/mcp.json'
      preLoaderRoute: typeof DotwellKnownMcpDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/signature-agent-card.json': {
      id: '/.well-known/signature-agent-card.json'
      path: '/.well-known/signature-agent-card.json'
      fullPath: '/.well-known/signature-agent-card.json'
      preLoaderRoute: typeof DotwellKnownSignatureAgentCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/public': {
      id: '/agents/public'
      path: '/agents/public'
      fullPath: '/agents/public'
      preLoaderRoute: typeof AgentsPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/search': {
      id: '/agents/search'
      path: '/agents/search'
      fullPath: '/agents/search'
      preLoaderRoute: typeof AgentsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a2a': {
      id: '/api/a2a'
      path: '/api/a2a'
      fullPath: '/api/a2a'
      preLoaderRoute: typeof ApiA2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/counters': {
      id: '/api/counters'
      path: '/api/counters'
      fullPath: '/api/counters'
      preLoaderRoute: typeof ApiCountersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/growth': {
      id: '/api/growth'
      path: '/api/growth'
      fullPath: '/api/growth'
      preLoaderRoute: typeof ApiGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listing-lanes': {
      id: '/api/listing-lanes'
      path: '/api/listing-lanes'
      fullPath: '/api/listing-lanes'
      preLoaderRoute: typeof ApiListingLanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match': {
      id: '/api/match'
      path: '/api/match'
      fullPath: '/api/match'
      preLoaderRoute: typeof ApiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protocol': {
      id: '/api/protocol'
      path: '/api/protocol'
      fullPath: '/api/protocol'
      preLoaderRoute: typeof ApiProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish': {
      id: '/api/publish'
      path: '/api/publish'
      fullPath: '/api/publish'
      preLoaderRoute: typeof ApiPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/score': {
      id: '/api/score'
      path: '/api/score'
      fullPath: '/api/score'
      preLoaderRoute: typeof ApiScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/talk': {
      id: '/api/talk'
      path: '/api/talk'
      fullPath: '/api/talk'
      preLoaderRoute: typeof ApiTalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge/$kind': {
      id: '/badge/$kind'
      path: '/badge/$kind'
      fullPath: '/badge/$kind'
      preLoaderRoute: typeof BadgeKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-agents/': {
      id: '/for-agents/'
      path: '/for-agents'
      fullPath: '/for-agents/'
      preLoaderRoute: typeof ForAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/status': {
      id: '/list/status'
      path: '/status'
      fullPath: '/list/status'
      preLoaderRoute: typeof ListStatusRouteImport
      parentRoute: typeof ListRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/improvement-log': {
      id: '/products/improvement-log'
      path: '/products/improvement-log'
      fullPath: '/products/improvement-log'
      preLoaderRoute: typeof ProductsImprovementLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/roadmap': {
      id: '/products/roadmap'
      path: '/products/roadmap'
      fullPath: '/products/roadmap'
      preLoaderRoute: typeof ProductsRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/success': {
      id: '/products/success'
      path: '/products/success'
      fullPath: '/products/success'
      preLoaderRoute: typeof ProductsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/dualregistry.md': {
      id: '/skills/dualregistry.md'
      path: '/skills/dualregistry.md'
      fullPath: '/skills/dualregistry.md'
      preLoaderRoute: typeof SkillsDualregistryDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/server-card': {
      id: '/.well-known/mcp/server-card'
      path: '/.well-known/mcp/server-card'
      fullPath: '/.well-known/mcp/server-card'
      preLoaderRoute: typeof DotwellKnownMcpServerCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ard/search': {
      id: '/api/ard/search'
      path: '/api/ard/search'
      fullPath: '/api/ard/search'
      preLoaderRoute: typeof ApiArdSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/prefilter': {
      id: '/api/cron/prefilter'
      path: '/api/cron/prefilter'
      fullPath: '/api/cron/prefilter'
      preLoaderRoute: typeof ApiCronPrefilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/probe': {
      id: '/api/cron/probe'
      path: '/api/cron/probe'
      fullPath: '/api/cron/probe'
      preLoaderRoute: typeof ApiCronProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dns/mcp-status': {
      id: '/api/dns/mcp-status'
      path: '/api/dns/mcp-status'
      fullPath: '/api/dns/mcp-status'
      preLoaderRoute: typeof ApiDnsMcpStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/funnel/': {
      id: '/api/funnel/'
      path: '/api/funnel'
      fullPath: '/api/funnel/'
      preLoaderRoute: typeof ApiFunnelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listings/active': {
      id: '/api/listings/active'
      path: '/api/listings/active'
      fullPath: '/api/listings/active'
      preLoaderRoute: typeof ApiListingsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listings/status': {
      id: '/api/listings/status'
      path: '/api/listings/status'
      fullPath: '/api/listings/status'
      preLoaderRoute: typeof ApiListingsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-registry/publish-status': {
      id: '/api/mcp-registry/publish-status'
      path: '/api/mcp-registry/publish-status'
      fullPath: '/api/mcp-registry/publish-status'
      preLoaderRoute: typeof ApiMcpRegistryPublishStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-registry/server.json': {
      id: '/api/mcp-registry/server.json'
      path: '/api/mcp-registry/server.json'
      fullPath: '/api/mcp-registry/server.json'
      preLoaderRoute: typeof ApiMcpRegistryServerDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/agent-runs': {
      id: '/api/ops/agent-runs'
      path: '/api/ops/agent-runs'
      fullPath: '/api/ops/agent-runs'
      preLoaderRoute: typeof ApiOpsAgentRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/cloudflare-apply': {
      id: '/api/ops/cloudflare-apply'
      path: '/api/ops/cloudflare-apply'
      fullPath: '/api/ops/cloudflare-apply'
      preLoaderRoute: typeof ApiOpsCloudflareApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/vercel-cost': {
      id: '/api/ops/vercel-cost'
      path: '/api/ops/vercel-cost'
      fullPath: '/api/ops/vercel-cost'
      preLoaderRoute: typeof ApiOpsVercelCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/probes/': {
      id: '/api/probes/'
      path: '/api/probes'
      fullPath: '/api/probes/'
      preLoaderRoute: typeof ApiProbesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/access': {
      id: '/api/products/access'
      path: '/api/products/access'
      fullPath: '/api/products/access'
      preLoaderRoute: typeof ApiProductsAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/agent': {
      id: '/api/products/agent'
      path: '/api/products/agent'
      fullPath: '/api/products/agent'
      preLoaderRoute: typeof ApiProductsAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/agentfinder': {
      id: '/api/products/agentfinder'
      path: '/api/products/agentfinder'
      fullPath: '/api/products/agentfinder'
      preLoaderRoute: typeof ApiProductsAgentfinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/autocatalysis': {
      id: '/api/products/autocatalysis'
      path: '/api/products/autocatalysis'
      fullPath: '/api/products/autocatalysis'
      preLoaderRoute: typeof ApiProductsAutocatalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/checkout': {
      id: '/api/products/checkout'
      path: '/api/products/checkout'
      fullPath: '/api/products/checkout'
      preLoaderRoute: typeof ApiProductsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/confirm': {
      id: '/api/products/confirm'
      path: '/api/products/confirm'
      fullPath: '/api/products/confirm'
      preLoaderRoute: typeof ApiProductsConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/conversion': {
      id: '/api/products/conversion'
      path: '/api/products/conversion'
      fullPath: '/api/products/conversion'
      preLoaderRoute: typeof ApiProductsConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/conversion-pressure': {
      id: '/api/products/conversion-pressure'
      path: '/api/products/conversion-pressure'
      fullPath: '/api/products/conversion-pressure'
      preLoaderRoute: typeof ApiProductsConversionPressureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/demo': {
      id: '/api/products/demo'
      path: '/api/products/demo'
      fullPath: '/api/products/demo'
      preLoaderRoute: typeof ApiProductsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/demo-confirm': {
      id: '/api/products/demo-confirm'
      path: '/api/products/demo-confirm'
      fullPath: '/api/products/demo-confirm'
      preLoaderRoute: typeof ApiProductsDemoConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/demo-nudge': {
      id: '/api/products/demo-nudge'
      path: '/api/products/demo-nudge'
      fullPath: '/api/products/demo-nudge'
      preLoaderRoute: typeof ApiProductsDemoNudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/discovery-pack': {
      id: '/api/products/discovery-pack'
      path: '/api/products/discovery-pack'
      fullPath: '/api/products/discovery-pack'
      preLoaderRoute: typeof ApiProductsDiscoveryPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/dual-strategy': {
      id: '/api/products/dual-strategy'
      path: '/api/products/dual-strategy'
      fullPath: '/api/products/dual-strategy'
      preLoaderRoute: typeof ApiProductsDualStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/exonomics': {
      id: '/api/products/exonomics'
      path: '/api/products/exonomics'
      fullPath: '/api/products/exonomics'
      preLoaderRoute: typeof ApiProductsExonomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/export': {
      id: '/api/products/export'
      path: '/api/products/export'
      fullPath: '/api/products/export'
      preLoaderRoute: typeof ApiProductsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/federation': {
      id: '/api/products/federation'
      path: '/api/products/federation'
      fullPath: '/api/products/federation'
      preLoaderRoute: typeof ApiProductsFederationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/feedback': {
      id: '/api/products/feedback'
      path: '/api/products/feedback'
      fullPath: '/api/products/feedback'
      preLoaderRoute: typeof ApiProductsFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/feedback-drive': {
      id: '/api/products/feedback-drive'
      path: '/api/products/feedback-drive'
      fullPath: '/api/products/feedback-drive'
      preLoaderRoute: typeof ApiProductsFeedbackDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/first-principles': {
      id: '/api/products/first-principles'
      path: '/api/products/first-principles'
      fullPath: '/api/products/first-principles'
      preLoaderRoute: typeof ApiProductsFirstPrinciplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/founding-dogfood': {
      id: '/api/products/founding-dogfood'
      path: '/api/products/founding-dogfood'
      fullPath: '/api/products/founding-dogfood'
      preLoaderRoute: typeof ApiProductsFoundingDogfoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/go-harder': {
      id: '/api/products/go-harder'
      path: '/api/products/go-harder'
      fullPath: '/api/products/go-harder'
      preLoaderRoute: typeof ApiProductsGoHarderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/improvement-log': {
      id: '/api/products/improvement-log'
      path: '/api/products/improvement-log'
      fullPath: '/api/products/improvement-log'
      preLoaderRoute: typeof ApiProductsImprovementLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/interop': {
      id: '/api/products/interop'
      path: '/api/products/interop'
      fullPath: '/api/products/interop'
      preLoaderRoute: typeof ApiProductsInteropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/learning': {
      id: '/api/products/learning'
      path: '/api/products/learning'
      fullPath: '/api/products/learning'
      preLoaderRoute: typeof ApiProductsLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/lifecycle': {
      id: '/api/products/lifecycle'
      path: '/api/products/lifecycle'
      fullPath: '/api/products/lifecycle'
      preLoaderRoute: typeof ApiProductsLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/mail': {
      id: '/api/products/mail'
      path: '/api/products/mail'
      fullPath: '/api/products/mail'
      preLoaderRoute: typeof ApiProductsMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/preferences': {
      id: '/api/products/preferences'
      path: '/api/products/preferences'
      fullPath: '/api/products/preferences'
      preLoaderRoute: typeof ApiProductsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/preview': {
      id: '/api/products/preview'
      path: '/api/products/preview'
      fullPath: '/api/products/preview'
      preLoaderRoute: typeof ApiProductsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/reciprocity': {
      id: '/api/products/reciprocity'
      path: '/api/products/reciprocity'
      fullPath: '/api/products/reciprocity'
      preLoaderRoute: typeof ApiProductsReciprocityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/reply-capture': {
      id: '/api/products/reply-capture'
      path: '/api/products/reply-capture'
      fullPath: '/api/products/reply-capture'
      preLoaderRoute: typeof ApiProductsReplyCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/review': {
      id: '/api/products/review'
      path: '/api/products/review'
      fullPath: '/api/products/review'
      preLoaderRoute: typeof ApiProductsReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/roadmap': {
      id: '/api/products/roadmap'
      path: '/api/products/roadmap'
      fullPath: '/api/products/roadmap'
      preLoaderRoute: typeof ApiProductsRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/run': {
      id: '/api/products/run'
      path: '/api/products/run'
      fullPath: '/api/products/run'
      preLoaderRoute: typeof ApiProductsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/self-loop': {
      id: '/api/products/self-loop'
      path: '/api/products/self-loop'
      fullPath: '/api/products/self-loop'
      preLoaderRoute: typeof ApiProductsSelfLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/ship-cadence': {
      id: '/api/products/ship-cadence'
      path: '/api/products/ship-cadence'
      fullPath: '/api/products/ship-cadence'
      preLoaderRoute: typeof ApiProductsShipCadenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/stigmergy': {
      id: '/api/products/stigmergy'
      path: '/api/products/stigmergy'
      fullPath: '/api/products/stigmergy'
      preLoaderRoute: typeof ApiProductsStigmergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/verify': {
      id: '/api/products/verify'
      path: '/api/products/verify'
      fullPath: '/api/products/verify'
      preLoaderRoute: typeof ApiProductsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/webhook': {
      id: '/api/products/webhook'
      path: '/api/products/webhook'
      fullPath: '/api/products/webhook'
      preLoaderRoute: typeof ApiProductsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/wtp': {
      id: '/api/products/wtp'
      path: '/api/products/wtp'
      fullPath: '/api/products/wtp'
      preLoaderRoute: typeof ApiProductsWtpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ListRouteChildren {
  ListStatusRoute: typeof ListStatusRoute
}

const ListRouteChildren: ListRouteChildren = {
  ListStatusRoute: ListStatusRoute,
}

const ListRouteWithChildren = ListRoute._addFileChildren(ListRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentmapDotjsonRoute: AgentmapDotjsonRoute,
  AiDottxtRoute: AiDottxtRoute,
  DiscoveryDotjsonRoute: DiscoveryDotjsonRoute,
  GrowRoute: GrowRoute,
  ListRoute: ListRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  RobotsAgentDottxtRoute: RobotsAgentDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillDotjsonRoute: SkillDotjsonRoute,
  TalkRoute: TalkRoute,
  DotwellKnownA2aCardDotjsonRoute: DotwellKnownA2aCardDotjsonRoute,
  DotwellKnownAgentCardDotjsonRoute: DotwellKnownAgentCardDotjsonRoute,
  DotwellKnownAgentDescriptionsRoute: DotwellKnownAgentDescriptionsRoute,
  DotwellKnownAgentDotjsonRoute: DotwellKnownAgentDotjsonRoute,
  DotwellKnownAgentmapDotjsonRoute: DotwellKnownAgentmapDotjsonRoute,
  DotwellKnownAgentsRoute: DotwellKnownAgentsRoute,
  DotwellKnownAiCatalogDotjsonRoute: DotwellKnownAiCatalogDotjsonRoute,
  DotwellKnownHttpMessageSignaturesDirectoryRoute:
    DotwellKnownHttpMessageSignaturesDirectoryRoute,
  DotwellKnownJwksDotjsonRoute: DotwellKnownJwksDotjsonRoute,
  DotwellKnownMcpRegistryAuthRoute: DotwellKnownMcpRegistryAuthRoute,
  DotwellKnownMcpDotjsonRoute: DotwellKnownMcpDotjsonRoute,
  DotwellKnownSignatureAgentCardDotjsonRoute:
    DotwellKnownSignatureAgentCardDotjsonRoute,
  AgentsPublicRoute: AgentsPublicRoute,
  AgentsSearchRoute: AgentsSearchRoute,
  ApiA2aRoute: ApiA2aRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiCountersRoute: ApiCountersRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiGrowthRoute: ApiGrowthRoute,
  ApiListingLanesRoute: ApiListingLanesRoute,
  ApiMatchRoute: ApiMatchRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiProtocolRoute: ApiProtocolRoute,
  ApiPublishRoute: ApiPublishRoute,
  ApiScoreRoute: ApiScoreRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiTalkRoute: ApiTalkRoute,
  BadgeKindRoute: BadgeKindRoute,
  ProductsImprovementLogRoute: ProductsImprovementLogRoute,
  ProductsRoadmapRoute: ProductsRoadmapRoute,
  ProductsSuccessRoute: ProductsSuccessRoute,
  SkillsDualregistryDotmdRoute: SkillsDualregistryDotmdRoute,
  ForAgentsIndexRoute: ForAgentsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  DotwellKnownMcpServerCardRoute: DotwellKnownMcpServerCardRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  ApiArdSearchRoute: ApiArdSearchRoute,
  ApiCronPrefilterRoute: ApiCronPrefilterRoute,
  ApiCronProbeRoute: ApiCronProbeRoute,
  ApiDnsMcpStatusRoute: ApiDnsMcpStatusRoute,
  ApiListingsActiveRoute: ApiListingsActiveRoute,
  ApiListingsStatusRoute: ApiListingsStatusRoute,
  ApiMcpRegistryPublishStatusRoute: ApiMcpRegistryPublishStatusRoute,
  ApiMcpRegistryServerDotjsonRoute: ApiMcpRegistryServerDotjsonRoute,
  ApiOpsAgentRunsRoute: ApiOpsAgentRunsRoute,
  ApiOpsCloudflareApplyRoute: ApiOpsCloudflareApplyRoute,
  ApiOpsVercelCostRoute: ApiOpsVercelCostRoute,
  ApiProductsAccessRoute: ApiProductsAccessRoute,
  ApiProductsAgentRoute: ApiProductsAgentRoute,
  ApiProductsAgentfinderRoute: ApiProductsAgentfinderRoute,
  ApiProductsAutocatalysisRoute: ApiProductsAutocatalysisRoute,
  ApiProductsCheckoutRoute: ApiProductsCheckoutRoute,
  ApiProductsConfirmRoute: ApiProductsConfirmRoute,
  ApiProductsConversionRoute: ApiProductsConversionRoute,
  ApiProductsConversionPressureRoute: ApiProductsConversionPressureRoute,
  ApiProductsDemoRoute: ApiProductsDemoRoute,
  ApiProductsDemoConfirmRoute: ApiProductsDemoConfirmRoute,
  ApiProductsDemoNudgeRoute: ApiProductsDemoNudgeRoute,
  ApiProductsDiscoveryPackRoute: ApiProductsDiscoveryPackRoute,
  ApiProductsDualStrategyRoute: ApiProductsDualStrategyRoute,
  ApiProductsExonomicsRoute: ApiProductsExonomicsRoute,
  ApiProductsExportRoute: ApiProductsExportRoute,
  ApiProductsFederationRoute: ApiProductsFederationRoute,
  ApiProductsFeedbackRoute: ApiProductsFeedbackRoute,
  ApiProductsFeedbackDriveRoute: ApiProductsFeedbackDriveRoute,
  ApiProductsFirstPrinciplesRoute: ApiProductsFirstPrinciplesRoute,
  ApiProductsFoundingDogfoodRoute: ApiProductsFoundingDogfoodRoute,
  ApiProductsGoHarderRoute: ApiProductsGoHarderRoute,
  ApiProductsImprovementLogRoute: ApiProductsImprovementLogRoute,
  ApiProductsInteropRoute: ApiProductsInteropRoute,
  ApiProductsLearningRoute: ApiProductsLearningRoute,
  ApiProductsLifecycleRoute: ApiProductsLifecycleRoute,
  ApiProductsMailRoute: ApiProductsMailRoute,
  ApiProductsPreferencesRoute: ApiProductsPreferencesRoute,
  ApiProductsPreviewRoute: ApiProductsPreviewRoute,
  ApiProductsReciprocityRoute: ApiProductsReciprocityRoute,
  ApiProductsReplyCaptureRoute: ApiProductsReplyCaptureRoute,
  ApiProductsReviewRoute: ApiProductsReviewRoute,
  ApiProductsRoadmapRoute: ApiProductsRoadmapRoute,
  ApiProductsRunRoute: ApiProductsRunRoute,
  ApiProductsSelfLoopRoute: ApiProductsSelfLoopRoute,
  ApiProductsShipCadenceRoute: ApiProductsShipCadenceRoute,
  ApiProductsStigmergyRoute: ApiProductsStigmergyRoute,
  ApiProductsVerifyRoute: ApiProductsVerifyRoute,
  ApiProductsWebhookRoute: ApiProductsWebhookRoute,
  ApiProductsWtpRoute: ApiProductsWtpRoute,
  ApiFunnelIndexRoute: ApiFunnelIndexRoute,
  ApiProbesIndexRoute: ApiProbesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
