/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoveryDotjsonRouteImport } from './routes/discovery[.]json'
import { Route as ListRouteImport } from './routes/list'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as SkillDotjsonRouteImport } from './routes/skill[.]json'
import { Route as DotwellKnownAgentDotjsonRouteImport } from './routes/[.]well-known/agent[.]json'
import { Route as DotwellKnownAgentsRouteImport } from './routes/[.]well-known/agents'
import { Route as AgentsPublicRouteImport } from './routes/agents/public'
import { Route as AgentsSearchRouteImport } from './routes/agents/search'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiGrowthRouteImport } from './routes/api/growth'
import { Route as ApiListingLanesRouteImport } from './routes/api/listing-lanes'
import { Route as ApiProtocolRouteImport } from './routes/api/protocol'
import { Route as ApiPublishRouteImport } from './routes/api/publish'
import { Route as ApiScoreRouteImport } from './routes/api/score'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as BadgeKindRouteImport } from './routes/badge/$kind'
import { Route as ForAgentsIndexRouteImport } from './routes/for-agents/index'
import { Route as ListStatusRouteImport } from './routes/list/status'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsImprovementLogRouteImport } from './routes/products/improvement-log'
import { Route as ProductsRoadmapRouteImport } from './routes/products/roadmap'
import { Route as ProductsSuccessRouteImport } from './routes/products/success'
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from './routes/[.]well-known/mcp/server-card[.]json'
import { Route as ApiFunnelIndexRouteImport } from './routes/api/funnel/index'
import { Route as ApiListingsActiveRouteImport } from './routes/api/listings/active'
import { Route as ApiListingsStatusRouteImport } from './routes/api/listings/status'
import { Route as ApiProbesIndexRouteImport } from './routes/api/probes/index'
import { Route as ApiProductsAccessRouteImport } from './routes/api/products/access'
import { Route as ApiProductsAgentRouteImport } from './routes/api/products/agent'
import { Route as ApiProductsCheckoutRouteImport } from './routes/api/products/checkout'
import { Route as ApiProductsConfirmRouteImport } from './routes/api/products/confirm'
import { Route as ApiProductsConversionRouteImport } from './routes/api/products/conversion'
import { Route as ApiProductsDemoRouteImport } from './routes/api/products/demo'
import { Route as ApiProductsDemoConfirmRouteImport } from './routes/api/products/demo-confirm'
import { Route as ApiProductsExportRouteImport } from './routes/api/products/export'
import { Route as ApiProductsFeedbackRouteImport } from './routes/api/products/feedback'
import { Route as ApiProductsFeedbackDriveRouteImport } from './routes/api/products/feedback-drive'
import { Route as ApiProductsImprovementLogRouteImport } from './routes/api/products/improvement-log'
import { Route as ApiProductsLearningRouteImport } from './routes/api/products/learning'
import { Route as ApiProductsLifecycleRouteImport } from './routes/api/products/lifecycle'
import { Route as ApiProductsMailRouteImport } from './routes/api/products/mail'
import { Route as ApiProductsPreferencesRouteImport } from './routes/api/products/preferences'
import { Route as ApiProductsPreviewRouteImport } from './routes/api/products/preview'
import { Route as ApiProductsReviewRouteImport } from './routes/api/products/review'
import { Route as ApiProductsRoadmapRouteImport } from './routes/api/products/roadmap'
import { Route as ApiProductsRunRouteImport } from './routes/api/products/run'
import { Route as ApiProductsSelfLoopRouteImport } from './routes/api/products/self-loop'
import { Route as ApiProductsShipCadenceRouteImport } from './routes/api/products/ship-cadence'
import { Route as ApiProductsVerifyRouteImport } from './routes/api/products/verify'
import { Route as ApiProductsWebhookRouteImport } from './routes/api/products/webhook'
import { Route as ApiProductsWtpRouteImport } from './routes/api/products/wtp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryDotjsonRoute = DiscoveryDotjsonRouteImport.update({
  id: '/discovery.json',
  path: '/discovery.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillDotjsonRoute = SkillDotjsonRouteImport.update({
  id: '/skill.json',
  path: '/skill.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentDotjsonRoute =
  DotwellKnownAgentDotjsonRouteImport.update({
    id: '/.well-known/agent.json',
    path: '/.well-known/agent.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentsRoute = DotwellKnownAgentsRouteImport.update({
  id: '/.well-known/agents',
  path: '/.well-known/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsPublicRoute = AgentsPublicRouteImport.update({
  id: '/agents/public',
  path: '/agents/public',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSearchRoute = AgentsSearchRouteImport.update({
  id: '/agents/search',
  path: '/agents/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrowthRoute = ApiGrowthRouteImport.update({
  id: '/api/growth',
  path: '/api/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListingLanesRoute = ApiListingLanesRouteImport.update({
  id: '/api/listing-lanes',
  path: '/api/listing-lanes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtocolRoute = ApiProtocolRouteImport.update({
  id: '/api/protocol',
  path: '/api/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishRoute = ApiPublishRouteImport.update({
  id: '/api/publish',
  path: '/api/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoreRoute = ApiScoreRouteImport.update({
  id: '/api/score',
  path: '/api/score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgeKindRoute = BadgeKindRouteImport.update({
  id: '/badge/$kind',
  path: '/badge/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgentsIndexRoute = ForAgentsIndexRouteImport.update({
  id: '/for-agents/',
  path: '/for-agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListStatusRoute = ListStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ListRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsImprovementLogRoute = ProductsImprovementLogRouteImport.update({
  id: '/products/improvement-log',
  path: '/products/improvement-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoadmapRoute = ProductsRoadmapRouteImport.update({
  id: '/products/roadmap',
  path: '/products/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSuccessRoute = ProductsSuccessRouteImport.update({
  id: '/products/success',
  path: '/products/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/.well-known/mcp/server-card.json',
    path: '/.well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFunnelIndexRoute = ApiFunnelIndexRouteImport.update({
  id: '/api/funnel/',
  path: '/api/funnel/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListingsActiveRoute = ApiListingsActiveRouteImport.update({
  id: '/api/listings/active',
  path: '/api/listings/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListingsStatusRoute = ApiListingsStatusRouteImport.update({
  id: '/api/listings/status',
  path: '/api/listings/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProbesIndexRoute = ApiProbesIndexRouteImport.update({
  id: '/api/probes/',
  path: '/api/probes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsAccessRoute = ApiProductsAccessRouteImport.update({
  id: '/api/products/access',
  path: '/api/products/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsAgentRoute = ApiProductsAgentRouteImport.update({
  id: '/api/products/agent',
  path: '/api/products/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsCheckoutRoute = ApiProductsCheckoutRouteImport.update({
  id: '/api/products/checkout',
  path: '/api/products/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsConfirmRoute = ApiProductsConfirmRouteImport.update({
  id: '/api/products/confirm',
  path: '/api/products/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsConversionRoute = ApiProductsConversionRouteImport.update({
  id: '/api/products/conversion',
  path: '/api/products/conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsDemoRoute = ApiProductsDemoRouteImport.update({
  id: '/api/products/demo',
  path: '/api/products/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsDemoConfirmRoute = ApiProductsDemoConfirmRouteImport.update({
  id: '/api/products/demo-confirm',
  path: '/api/products/demo-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsExportRoute = ApiProductsExportRouteImport.update({
  id: '/api/products/export',
  path: '/api/products/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsFeedbackRoute = ApiProductsFeedbackRouteImport.update({
  id: '/api/products/feedback',
  path: '/api/products/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsFeedbackDriveRoute =
  ApiProductsFeedbackDriveRouteImport.update({
    id: '/api/products/feedback-drive',
    path: '/api/products/feedback-drive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProductsImprovementLogRoute =
  ApiProductsImprovementLogRouteImport.update({
    id: '/api/products/improvement-log',
    path: '/api/products/improvement-log',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProductsLearningRoute = ApiProductsLearningRouteImport.update({
  id: '/api/products/learning',
  path: '/api/products/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsLifecycleRoute = ApiProductsLifecycleRouteImport.update({
  id: '/api/products/lifecycle',
  path: '/api/products/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsMailRoute = ApiProductsMailRouteImport.update({
  id: '/api/products/mail',
  path: '/api/products/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsPreferencesRoute = ApiProductsPreferencesRouteImport.update({
  id: '/api/products/preferences',
  path: '/api/products/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsPreviewRoute = ApiProductsPreviewRouteImport.update({
  id: '/api/products/preview',
  path: '/api/products/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsReviewRoute = ApiProductsReviewRouteImport.update({
  id: '/api/products/review',
  path: '/api/products/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoadmapRoute = ApiProductsRoadmapRouteImport.update({
  id: '/api/products/roadmap',
  path: '/api/products/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRunRoute = ApiProductsRunRouteImport.update({
  id: '/api/products/run',
  path: '/api/products/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsSelfLoopRoute = ApiProductsSelfLoopRouteImport.update({
  id: '/api/products/self-loop',
  path: '/api/products/self-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsShipCadenceRoute = ApiProductsShipCadenceRouteImport.update({
  id: '/api/products/ship-cadence',
  path: '/api/products/ship-cadence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsVerifyRoute = ApiProductsVerifyRouteImport.update({
  id: '/api/products/verify',
  path: '/api/products/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsWebhookRoute = ApiProductsWebhookRouteImport.update({
  id: '/api/products/webhook',
  path: '/api/products/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsWtpRoute = ApiProductsWtpRouteImport.update({
  id: '/api/products/wtp',
  path: '/api/products/wtp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discovery.json': typeof DiscoveryDotjsonRoute
  '/list': typeof ListRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/skill.json': typeof SkillDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/agents': typeof DotwellKnownAgentsRoute
  '/agents/public': typeof AgentsPublicRoute
  '/agents/search': typeof AgentsSearchRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/growth': typeof ApiGrowthRoute
  '/api/listing-lanes': typeof ApiListingLanesRoute
  '/api/protocol': typeof ApiProtocolRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/score': typeof ApiScoreRoute
  '/api/stats': typeof ApiStatsRoute
  '/badge/$kind': typeof BadgeKindRoute
  '/list/status': typeof ListStatusRoute
  '/products/improvement-log': typeof ProductsImprovementLogRoute
  '/products/roadmap': typeof ProductsRoadmapRoute
  '/products/success': typeof ProductsSuccessRoute
  '/for-agents/': typeof ForAgentsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/listings/active': typeof ApiListingsActiveRoute
  '/api/listings/status': typeof ApiListingsStatusRoute
  '/api/products/access': typeof ApiProductsAccessRoute
  '/api/products/agent': typeof ApiProductsAgentRoute
  '/api/products/checkout': typeof ApiProductsCheckoutRoute
  '/api/products/confirm': typeof ApiProductsConfirmRoute
  '/api/products/conversion': typeof ApiProductsConversionRoute
  '/api/products/demo': typeof ApiProductsDemoRoute
  '/api/products/demo-confirm': typeof ApiProductsDemoConfirmRoute
  '/api/products/export': typeof ApiProductsExportRoute
  '/api/products/feedback': typeof ApiProductsFeedbackRoute
  '/api/products/feedback-drive': typeof ApiProductsFeedbackDriveRoute
  '/api/products/improvement-log': typeof ApiProductsImprovementLogRoute
  '/api/products/learning': typeof ApiProductsLearningRoute
  '/api/products/lifecycle': typeof ApiProductsLifecycleRoute
  '/api/products/mail': typeof ApiProductsMailRoute
  '/api/products/preferences': typeof ApiProductsPreferencesRoute
  '/api/products/preview': typeof ApiProductsPreviewRoute
  '/api/products/review': typeof ApiProductsReviewRoute
  '/api/products/roadmap': typeof ApiProductsRoadmapRoute
  '/api/products/run': typeof ApiProductsRunRoute
  '/api/products/self-loop': typeof ApiProductsSelfLoopRoute
  '/api/products/ship-cadence': typeof ApiProductsShipCadenceRoute
  '/api/products/verify': typeof ApiProductsVerifyRoute
  '/api/products/webhook': typeof ApiProductsWebhookRoute
  '/api/products/wtp': typeof ApiProductsWtpRoute
  '/api/funnel/': typeof ApiFunnelIndexRoute
  '/api/probes/': typeof ApiProbesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discovery.json': typeof DiscoveryDotjsonRoute
  '/list': typeof ListRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/skill.json': typeof SkillDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/agents': typeof DotwellKnownAgentsRoute
  '/agents/public': typeof AgentsPublicRoute
  '/agents/search': typeof AgentsSearchRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/growth': typeof ApiGrowthRoute
  '/api/listing-lanes': typeof ApiListingLanesRoute
  '/api/protocol': typeof ApiProtocolRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/score': typeof ApiScoreRoute
  '/api/stats': typeof ApiStatsRoute
  '/badge/$kind': typeof BadgeKindRoute
  '/list/status': typeof ListStatusRoute
  '/products/improvement-log': typeof ProductsImprovementLogRoute
  '/products/roadmap': typeof ProductsRoadmapRoute
  '/products/success': typeof ProductsSuccessRoute
  '/for-agents': typeof ForAgentsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/listings/active': typeof ApiListingsActiveRoute
  '/api/listings/status': typeof ApiListingsStatusRoute
  '/api/products/access': typeof ApiProductsAccessRoute
  '/api/products/agent': typeof ApiProductsAgentRoute
  '/api/products/checkout': typeof ApiProductsCheckoutRoute
  '/api/products/confirm': typeof ApiProductsConfirmRoute
  '/api/products/conversion': typeof ApiProductsConversionRoute
  '/api/products/demo': typeof ApiProductsDemoRoute
  '/api/products/demo-confirm': typeof ApiProductsDemoConfirmRoute
  '/api/products/export': typeof ApiProductsExportRoute
  '/api/products/feedback': typeof ApiProductsFeedbackRoute
  '/api/products/feedback-drive': typeof ApiProductsFeedbackDriveRoute
  '/api/products/improvement-log': typeof ApiProductsImprovementLogRoute
  '/api/products/learning': typeof ApiProductsLearningRoute
  '/api/products/lifecycle': typeof ApiProductsLifecycleRoute
  '/api/products/mail': typeof ApiProductsMailRoute
  '/api/products/preferences': typeof ApiProductsPreferencesRoute
  '/api/products/preview': typeof ApiProductsPreviewRoute
  '/api/products/review': typeof ApiProductsReviewRoute
  '/api/products/roadmap': typeof ApiProductsRoadmapRoute
  '/api/products/run': typeof ApiProductsRunRoute
  '/api/products/self-loop': typeof ApiProductsSelfLoopRoute
  '/api/products/ship-cadence': typeof ApiProductsShipCadenceRoute
  '/api/products/verify': typeof ApiProductsVerifyRoute
  '/api/products/webhook': typeof ApiProductsWebhookRoute
  '/api/products/wtp': typeof ApiProductsWtpRoute
  '/api/funnel': typeof ApiFunnelIndexRoute
  '/api/probes': typeof ApiProbesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discovery.json': typeof DiscoveryDotjsonRoute
  '/list': typeof ListRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/skill.json': typeof SkillDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/agents': typeof DotwellKnownAgentsRoute
  '/agents/public': typeof AgentsPublicRoute
  '/agents/search': typeof AgentsSearchRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/growth': typeof ApiGrowthRoute
  '/api/listing-lanes': typeof ApiListingLanesRoute
  '/api/protocol': typeof ApiProtocolRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/score': typeof ApiScoreRoute
  '/api/stats': typeof ApiStatsRoute
  '/badge/$kind': typeof BadgeKindRoute
  '/list/status': typeof ListStatusRoute
  '/products/improvement-log': typeof ProductsImprovementLogRoute
  '/products/roadmap': typeof ProductsRoadmapRoute
  '/products/success': typeof ProductsSuccessRoute
  '/for-agents/': typeof ForAgentsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/listings/active': typeof ApiListingsActiveRoute
  '/api/listings/status': typeof ApiListingsStatusRoute
  '/api/products/access': typeof ApiProductsAccessRoute
  '/api/products/agent': typeof ApiProductsAgentRoute
  '/api/products/checkout': typeof ApiProductsCheckoutRoute
  '/api/products/confirm': typeof ApiProductsConfirmRoute
  '/api/products/conversion': typeof ApiProductsConversionRoute
  '/api/products/demo': typeof ApiProductsDemoRoute
  '/api/products/demo-confirm': typeof ApiProductsDemoConfirmRoute
  '/api/products/export': typeof ApiProductsExportRoute
  '/api/products/feedback': typeof ApiProductsFeedbackRoute
  '/api/products/feedback-drive': typeof ApiProductsFeedbackDriveRoute
  '/api/products/improvement-log': typeof ApiProductsImprovementLogRoute
  '/api/products/learning': typeof ApiProductsLearningRoute
  '/api/products/lifecycle': typeof ApiProductsLifecycleRoute
  '/api/products/mail': typeof ApiProductsMailRoute
  '/api/products/preferences': typeof ApiProductsPreferencesRoute
  '/api/products/preview': typeof ApiProductsPreviewRoute
  '/api/products/review': typeof ApiProductsReviewRoute
  '/api/products/roadmap': typeof ApiProductsRoadmapRoute
  '/api/products/run': typeof ApiProductsRunRoute
  '/api/products/self-loop': typeof ApiProductsSelfLoopRoute
  '/api/products/ship-cadence': typeof ApiProductsShipCadenceRoute
  '/api/products/verify': typeof ApiProductsVerifyRoute
  '/api/products/webhook': typeof ApiProductsWebhookRoute
  '/api/products/wtp': typeof ApiProductsWtpRoute
  '/api/funnel/': typeof ApiFunnelIndexRoute
  '/api/probes/': typeof ApiProbesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discovery.json'
    | '/list'
    | '/llms.txt'
    | '/skill.json'
    | '/.well-known/agent.json'
    | '/.well-known/agents'
    | '/agents/public'
    | '/agents/search'
    | '/api/catalog'
    | '/api/categories'
    | '/api/dashboard'
    | '/api/growth'
    | '/api/listing-lanes'
    | '/api/protocol'
    | '/api/publish'
    | '/api/score'
    | '/api/stats'
    | '/badge/$kind'
    | '/list/status'
    | '/products/improvement-log'
    | '/products/roadmap'
    | '/products/success'
    | '/for-agents/'
    | '/products/'
    | '/.well-known/mcp/server-card.json'
    | '/api/listings/active'
    | '/api/listings/status'
    | '/api/products/access'
    | '/api/products/agent'
    | '/api/products/checkout'
    | '/api/products/confirm'
    | '/api/products/conversion'
    | '/api/products/demo'
    | '/api/products/demo-confirm'
    | '/api/products/export'
    | '/api/products/feedback'
    | '/api/products/feedback-drive'
    | '/api/products/improvement-log'
    | '/api/products/learning'
    | '/api/products/lifecycle'
    | '/api/products/mail'
    | '/api/products/preferences'
    | '/api/products/preview'
    | '/api/products/review'
    | '/api/products/roadmap'
    | '/api/products/run'
    | '/api/products/self-loop'
    | '/api/products/ship-cadence'
    | '/api/products/verify'
    | '/api/products/webhook'
    | '/api/products/wtp'
    | '/api/funnel/'
    | '/api/probes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discovery.json'
    | '/list'
    | '/llms.txt'
    | '/skill.json'
    | '/.well-known/agent.json'
    | '/.well-known/agents'
    | '/agents/public'
    | '/agents/search'
    | '/api/catalog'
    | '/api/categories'
    | '/api/dashboard'
    | '/api/growth'
    | '/api/listing-lanes'
    | '/api/protocol'
    | '/api/publish'
    | '/api/score'
    | '/api/stats'
    | '/badge/$kind'
    | '/list/status'
    | '/products/improvement-log'
    | '/products/roadmap'
    | '/products/success'
    | '/for-agents'
    | '/products'
    | '/.well-known/mcp/server-card.json'
    | '/api/listings/active'
    | '/api/listings/status'
    | '/api/products/access'
    | '/api/products/agent'
    | '/api/products/checkout'
    | '/api/products/confirm'
    | '/api/products/conversion'
    | '/api/products/demo'
    | '/api/products/demo-confirm'
    | '/api/products/export'
    | '/api/products/feedback'
    | '/api/products/feedback-drive'
    | '/api/products/improvement-log'
    | '/api/products/learning'
    | '/api/products/lifecycle'
    | '/api/products/mail'
    | '/api/products/preferences'
    | '/api/products/preview'
    | '/api/products/review'
    | '/api/products/roadmap'
    | '/api/products/run'
    | '/api/products/self-loop'
    | '/api/products/ship-cadence'
    | '/api/products/verify'
    | '/api/products/webhook'
    | '/api/products/wtp'
    | '/api/funnel'
    | '/api/probes'
  id:
    | '__root__'
    | '/'
    | '/discovery.json'
    | '/list'
    | '/llms.txt'
    | '/skill.json'
    | '/.well-known/agent.json'
    | '/.well-known/agents'
    | '/agents/public'
    | '/agents/search'
    | '/api/catalog'
    | '/api/categories'
    | '/api/dashboard'
    | '/api/growth'
    | '/api/listing-lanes'
    | '/api/protocol'
    | '/api/publish'
    | '/api/score'
    | '/api/stats'
    | '/badge/$kind'
    | '/list/status'
    | '/products/improvement-log'
    | '/products/roadmap'
    | '/products/success'
    | '/for-agents/'
    | '/products/'
    | '/.well-known/mcp/server-card.json'
    | '/api/listings/active'
    | '/api/listings/status'
    | '/api/products/access'
    | '/api/products/agent'
    | '/api/products/checkout'
    | '/api/products/confirm'
    | '/api/products/conversion'
    | '/api/products/demo'
    | '/api/products/demo-confirm'
    | '/api/products/export'
    | '/api/products/feedback'
    | '/api/products/feedback-drive'
    | '/api/products/improvement-log'
    | '/api/products/learning'
    | '/api/products/lifecycle'
    | '/api/products/mail'
    | '/api/products/preferences'
    | '/api/products/preview'
    | '/api/products/review'
    | '/api/products/roadmap'
    | '/api/products/run'
    | '/api/products/self-loop'
    | '/api/products/ship-cadence'
    | '/api/products/verify'
    | '/api/products/webhook'
    | '/api/products/wtp'
    | '/api/funnel/'
    | '/api/probes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoveryDotjsonRoute: typeof DiscoveryDotjsonRoute
  ListRoute: typeof ListRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SkillDotjsonRoute: typeof SkillDotjsonRoute
  DotwellKnownAgentDotjsonRoute: typeof DotwellKnownAgentDotjsonRoute
  DotwellKnownAgentsRoute: typeof DotwellKnownAgentsRoute
  AgentsPublicRoute: typeof AgentsPublicRoute
  AgentsSearchRoute: typeof AgentsSearchRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiGrowthRoute: typeof ApiGrowthRoute
  ApiListingLanesRoute: typeof ApiListingLanesRoute
  ApiProtocolRoute: typeof ApiProtocolRoute
  ApiPublishRoute: typeof ApiPublishRoute
  ApiScoreRoute: typeof ApiScoreRoute
  ApiStatsRoute: typeof ApiStatsRoute
  BadgeKindRoute: typeof BadgeKindRoute
  ProductsImprovementLogRoute: typeof ProductsImprovementLogRoute
  ProductsRoadmapRoute: typeof ProductsRoadmapRoute
  ProductsSuccessRoute: typeof ProductsSuccessRoute
  ForAgentsIndexRoute: typeof ForAgentsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute
  ApiListingsActiveRoute: typeof ApiListingsActiveRoute
  ApiListingsStatusRoute: typeof ApiListingsStatusRoute
  ApiProductsAccessRoute: typeof ApiProductsAccessRoute
  ApiProductsAgentRoute: typeof ApiProductsAgentRoute
  ApiProductsCheckoutRoute: typeof ApiProductsCheckoutRoute
  ApiProductsConfirmRoute: typeof ApiProductsConfirmRoute
  ApiProductsConversionRoute: typeof ApiProductsConversionRoute
  ApiProductsDemoRoute: typeof ApiProductsDemoRoute
  ApiProductsDemoConfirmRoute: typeof ApiProductsDemoConfirmRoute
  ApiProductsExportRoute: typeof ApiProductsExportRoute
  ApiProductsFeedbackRoute: typeof ApiProductsFeedbackRoute
  ApiProductsFeedbackDriveRoute: typeof ApiProductsFeedbackDriveRoute
  ApiProductsImprovementLogRoute: typeof ApiProductsImprovementLogRoute
  ApiProductsLearningRoute: typeof ApiProductsLearningRoute
  ApiProductsLifecycleRoute: typeof ApiProductsLifecycleRoute
  ApiProductsMailRoute: typeof ApiProductsMailRoute
  ApiProductsPreferencesRoute: typeof ApiProductsPreferencesRoute
  ApiProductsPreviewRoute: typeof ApiProductsPreviewRoute
  ApiProductsReviewRoute: typeof ApiProductsReviewRoute
  ApiProductsRoadmapRoute: typeof ApiProductsRoadmapRoute
  ApiProductsRunRoute: typeof ApiProductsRunRoute
  ApiProductsSelfLoopRoute: typeof ApiProductsSelfLoopRoute
  ApiProductsShipCadenceRoute: typeof ApiProductsShipCadenceRoute
  ApiProductsVerifyRoute: typeof ApiProductsVerifyRoute
  ApiProductsWebhookRoute: typeof ApiProductsWebhookRoute
  ApiProductsWtpRoute: typeof ApiProductsWtpRoute
  ApiFunnelIndexRoute: typeof ApiFunnelIndexRoute
  ApiProbesIndexRoute: typeof ApiProbesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery.json': {
      id: '/discovery.json'
      path: '/discovery.json'
      fullPath: '/discovery.json'
      preLoaderRoute: typeof DiscoveryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill.json': {
      id: '/skill.json'
      path: '/skill.json'
      fullPath: '/skill.json'
      preLoaderRoute: typeof SkillDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent.json': {
      id: '/.well-known/agent.json'
      path: '/.well-known/agent.json'
      fullPath: '/.well-known/agent.json'
      preLoaderRoute: typeof DotwellKnownAgentDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agents': {
      id: '/.well-known/agents'
      path: '/.well-known/agents'
      fullPath: '/.well-known/agents'
      preLoaderRoute: typeof DotwellKnownAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/public': {
      id: '/agents/public'
      path: '/agents/public'
      fullPath: '/agents/public'
      preLoaderRoute: typeof AgentsPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/search': {
      id: '/agents/search'
      path: '/agents/search'
      fullPath: '/agents/search'
      preLoaderRoute: typeof AgentsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/growth': {
      id: '/api/growth'
      path: '/api/growth'
      fullPath: '/api/growth'
      preLoaderRoute: typeof ApiGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listing-lanes': {
      id: '/api/listing-lanes'
      path: '/api/listing-lanes'
      fullPath: '/api/listing-lanes'
      preLoaderRoute: typeof ApiListingLanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protocol': {
      id: '/api/protocol'
      path: '/api/protocol'
      fullPath: '/api/protocol'
      preLoaderRoute: typeof ApiProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish': {
      id: '/api/publish'
      path: '/api/publish'
      fullPath: '/api/publish'
      preLoaderRoute: typeof ApiPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/score': {
      id: '/api/score'
      path: '/api/score'
      fullPath: '/api/score'
      preLoaderRoute: typeof ApiScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge/$kind': {
      id: '/badge/$kind'
      path: '/badge/$kind'
      fullPath: '/badge/$kind'
      preLoaderRoute: typeof BadgeKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-agents/': {
      id: '/for-agents/'
      path: '/for-agents'
      fullPath: '/for-agents/'
      preLoaderRoute: typeof ForAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/status': {
      id: '/list/status'
      path: '/status'
      fullPath: '/list/status'
      preLoaderRoute: typeof ListStatusRouteImport
      parentRoute: typeof ListRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/improvement-log': {
      id: '/products/improvement-log'
      path: '/products/improvement-log'
      fullPath: '/products/improvement-log'
      preLoaderRoute: typeof ProductsImprovementLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/roadmap': {
      id: '/products/roadmap'
      path: '/products/roadmap'
      fullPath: '/products/roadmap'
      preLoaderRoute: typeof ProductsRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/success': {
      id: '/products/success'
      path: '/products/success'
      fullPath: '/products/success'
      preLoaderRoute: typeof ProductsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/funnel/': {
      id: '/api/funnel/'
      path: '/api/funnel'
      fullPath: '/api/funnel/'
      preLoaderRoute: typeof ApiFunnelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listings/active': {
      id: '/api/listings/active'
      path: '/api/listings/active'
      fullPath: '/api/listings/active'
      preLoaderRoute: typeof ApiListingsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listings/status': {
      id: '/api/listings/status'
      path: '/api/listings/status'
      fullPath: '/api/listings/status'
      preLoaderRoute: typeof ApiListingsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/probes/': {
      id: '/api/probes/'
      path: '/api/probes'
      fullPath: '/api/probes/'
      preLoaderRoute: typeof ApiProbesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/access': {
      id: '/api/products/access'
      path: '/api/products/access'
      fullPath: '/api/products/access'
      preLoaderRoute: typeof ApiProductsAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/agent': {
      id: '/api/products/agent'
      path: '/api/products/agent'
      fullPath: '/api/products/agent'
      preLoaderRoute: typeof ApiProductsAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/checkout': {
      id: '/api/products/checkout'
      path: '/api/products/checkout'
      fullPath: '/api/products/checkout'
      preLoaderRoute: typeof ApiProductsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/confirm': {
      id: '/api/products/confirm'
      path: '/api/products/confirm'
      fullPath: '/api/products/confirm'
      preLoaderRoute: typeof ApiProductsConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/conversion': {
      id: '/api/products/conversion'
      path: '/api/products/conversion'
      fullPath: '/api/products/conversion'
      preLoaderRoute: typeof ApiProductsConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/demo': {
      id: '/api/products/demo'
      path: '/api/products/demo'
      fullPath: '/api/products/demo'
      preLoaderRoute: typeof ApiProductsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/demo-confirm': {
      id: '/api/products/demo-confirm'
      path: '/api/products/demo-confirm'
      fullPath: '/api/products/demo-confirm'
      preLoaderRoute: typeof ApiProductsDemoConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/export': {
      id: '/api/products/export'
      path: '/api/products/export'
      fullPath: '/api/products/export'
      preLoaderRoute: typeof ApiProductsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/feedback': {
      id: '/api/products/feedback'
      path: '/api/products/feedback'
      fullPath: '/api/products/feedback'
      preLoaderRoute: typeof ApiProductsFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/feedback-drive': {
      id: '/api/products/feedback-drive'
      path: '/api/products/feedback-drive'
      fullPath: '/api/products/feedback-drive'
      preLoaderRoute: typeof ApiProductsFeedbackDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/improvement-log': {
      id: '/api/products/improvement-log'
      path: '/api/products/improvement-log'
      fullPath: '/api/products/improvement-log'
      preLoaderRoute: typeof ApiProductsImprovementLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/learning': {
      id: '/api/products/learning'
      path: '/api/products/learning'
      fullPath: '/api/products/learning'
      preLoaderRoute: typeof ApiProductsLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/lifecycle': {
      id: '/api/products/lifecycle'
      path: '/api/products/lifecycle'
      fullPath: '/api/products/lifecycle'
      preLoaderRoute: typeof ApiProductsLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/mail': {
      id: '/api/products/mail'
      path: '/api/products/mail'
      fullPath: '/api/products/mail'
      preLoaderRoute: typeof ApiProductsMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/preferences': {
      id: '/api/products/preferences'
      path: '/api/products/preferences'
      fullPath: '/api/products/preferences'
      preLoaderRoute: typeof ApiProductsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/preview': {
      id: '/api/products/preview'
      path: '/api/products/preview'
      fullPath: '/api/products/preview'
      preLoaderRoute: typeof ApiProductsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/review': {
      id: '/api/products/review'
      path: '/api/products/review'
      fullPath: '/api/products/review'
      preLoaderRoute: typeof ApiProductsReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/roadmap': {
      id: '/api/products/roadmap'
      path: '/api/products/roadmap'
      fullPath: '/api/products/roadmap'
      preLoaderRoute: typeof ApiProductsRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/run': {
      id: '/api/products/run'
      path: '/api/products/run'
      fullPath: '/api/products/run'
      preLoaderRoute: typeof ApiProductsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/self-loop': {
      id: '/api/products/self-loop'
      path: '/api/products/self-loop'
      fullPath: '/api/products/self-loop'
      preLoaderRoute: typeof ApiProductsSelfLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/ship-cadence': {
      id: '/api/products/ship-cadence'
      path: '/api/products/ship-cadence'
      fullPath: '/api/products/ship-cadence'
      preLoaderRoute: typeof ApiProductsShipCadenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/verify': {
      id: '/api/products/verify'
      path: '/api/products/verify'
      fullPath: '/api/products/verify'
      preLoaderRoute: typeof ApiProductsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/webhook': {
      id: '/api/products/webhook'
      path: '/api/products/webhook'
      fullPath: '/api/products/webhook'
      preLoaderRoute: typeof ApiProductsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/wtp': {
      id: '/api/products/wtp'
      path: '/api/products/wtp'
      fullPath: '/api/products/wtp'
      preLoaderRoute: typeof ApiProductsWtpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ListRouteChildren {
  ListStatusRoute: typeof ListStatusRoute
}

const ListRouteChildren: ListRouteChildren = {
  ListStatusRoute: ListStatusRoute,
}

const ListRouteWithChildren = ListRoute._addFileChildren(ListRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoveryDotjsonRoute: DiscoveryDotjsonRoute,
  ListRoute: ListRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SkillDotjsonRoute: SkillDotjsonRoute,
  DotwellKnownAgentDotjsonRoute: DotwellKnownAgentDotjsonRoute,
  DotwellKnownAgentsRoute: DotwellKnownAgentsRoute,
  AgentsPublicRoute: AgentsPublicRoute,
  AgentsSearchRoute: AgentsSearchRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiGrowthRoute: ApiGrowthRoute,
  ApiListingLanesRoute: ApiListingLanesRoute,
  ApiProtocolRoute: ApiProtocolRoute,
  ApiPublishRoute: ApiPublishRoute,
  ApiScoreRoute: ApiScoreRoute,
  ApiStatsRoute: ApiStatsRoute,
  BadgeKindRoute: BadgeKindRoute,
  ProductsImprovementLogRoute: ProductsImprovementLogRoute,
  ProductsRoadmapRoute: ProductsRoadmapRoute,
  ProductsSuccessRoute: ProductsSuccessRoute,
  ForAgentsIndexRoute: ForAgentsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  ApiListingsActiveRoute: ApiListingsActiveRoute,
  ApiListingsStatusRoute: ApiListingsStatusRoute,
  ApiProductsAccessRoute: ApiProductsAccessRoute,
  ApiProductsAgentRoute: ApiProductsAgentRoute,
  ApiProductsCheckoutRoute: ApiProductsCheckoutRoute,
  ApiProductsConfirmRoute: ApiProductsConfirmRoute,
  ApiProductsConversionRoute: ApiProductsConversionRoute,
  ApiProductsDemoRoute: ApiProductsDemoRoute,
  ApiProductsDemoConfirmRoute: ApiProductsDemoConfirmRoute,
  ApiProductsExportRoute: ApiProductsExportRoute,
  ApiProductsFeedbackRoute: ApiProductsFeedbackRoute,
  ApiProductsFeedbackDriveRoute: ApiProductsFeedbackDriveRoute,
  ApiProductsImprovementLogRoute: ApiProductsImprovementLogRoute,
  ApiProductsLearningRoute: ApiProductsLearningRoute,
  ApiProductsLifecycleRoute: ApiProductsLifecycleRoute,
  ApiProductsMailRoute: ApiProductsMailRoute,
  ApiProductsPreferencesRoute: ApiProductsPreferencesRoute,
  ApiProductsPreviewRoute: ApiProductsPreviewRoute,
  ApiProductsReviewRoute: ApiProductsReviewRoute,
  ApiProductsRoadmapRoute: ApiProductsRoadmapRoute,
  ApiProductsRunRoute: ApiProductsRunRoute,
  ApiProductsSelfLoopRoute: ApiProductsSelfLoopRoute,
  ApiProductsShipCadenceRoute: ApiProductsShipCadenceRoute,
  ApiProductsVerifyRoute: ApiProductsVerifyRoute,
  ApiProductsWebhookRoute: ApiProductsWebhookRoute,
  ApiProductsWtpRoute: ApiProductsWtpRoute,
  ApiFunnelIndexRoute: ApiFunnelIndexRoute,
  ApiProbesIndexRoute: ApiProbesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
